
import { Level } from './types';

export const CURRICULUM: Level[] = [
  {
    id: 1,
    title: "ICT FOUNDATION (Beginner)",
    description: "Building the basic foundation of computing for absolute beginners.",
    target: "ကွန်ပျူတာ မသိသေးသူများအတွက်",
    topics: [
      "Computer ဆိုတာဘာလဲ (Introduction)",
      "Hardware နှင့် Software ကွာခြားချက်",
      "Input Devices (Keyboard, Mouse, Scanner)",
      "Output Devices (Monitor, Printer, Speaker)",
      "System Unit နှင့် CPU အကြောင်း",
      "RAM နှင့် Storage (HDD/SSD) ကွာခြားချက်",
      "Laptop နှင့် Desktop ရွေးချယ်နည်း",
      "Computer စနစ်တကျ ဖွင့်နည်း/ပိတ်နည်း",
      "Mouse အသုံးပြုနည်း (Click, Double Click, Drag)",
      "Keyboard Layout နှင့် Function Keys များ",
      "Operating System (Windows) အခြေခံ",
      "Bit နှင့် Byte (Data Units) အကြောင်း",
      "Computer Ports များ (USB, HDMI, VGA)",
      "Power Supply နှင့် UPS အကြောင်း",
      "Motherboard အခြေခံ နားလည်မှု",
      "Graphics Card (GPU) ဆိုတာဘာလဲ",
      "External Storage (Pen Drive, Hard Drive)",
      "Computer Maintenance အခြေခံ",
      "Dusting နှင့် Cleaning လုပ်နည်း",
      "Ergonomics (ထိုင်ပုံထိုင်နည်း စနစ်တကျ)",
      "Computer Virus ဆိုတာဘာလဲ",
      "Antivirus အခြေခံ သိကောင်းစရာ",
      "Software Installation အခြေခံ",
      "Freeware vs Paid Software",
      "Mobile vs Computer ကွာခြားချက်",
      "Cloud Computing အခြေခံ",
      "Data Backup လုပ်ခြင်း၏ အရေးကြီးပုံ",
      "IT နယ်ပယ်ရှိ Career များ",
      "Digital Citizenship အခြေခံ",
      "BIOS Setup အခြေခံ နားလည်မှု",
      "Firmware vs Software",
      "Legacy vs UEFI Systems",
      "Computer Specs ဖတ်နည်း (Specs Reading)",
      "Overclocking အခြေခံ သိကောင်းစရာ",
      "Solid State Drive (NVMe vs SATA)",
      "Network Interface Card (NIC)",
      "Sound Card နှင့် Audio Processing",
      "Optical Drives (DVD/Blu-ray) အကြောင်း",
      "Virtualization အခြေခံ (VMware/VirtualBox)",
      "Mainframe vs Supercomputer",
      "Embedded Systems အကြောင်း",
      "Algorithm အခြေခံ နားလည်မှု",
      "Binary Number System Intro",
      "ASCII နှင့် Unicode အခြေခံ",
      "Computer History (First to Fifth Generation)",
      "Transistors နှင့် Integrated Circuits",
      "Microprocessor Evolution",
      "Motherboard Form Factors (ATX, ITX)",
      "Chipset နှင့် Bus Speed အကြောင်း",
      "Cooling Systems (Air vs Liquid)",
      "Power Supply Certification (80 Plus)",
      "Input Lag နှင့် Response Time",
      "Resolution (HD, FHD, 4K) အကြောင်း",
      "Refresh Rate (Hz) နှင့် FPS",
      "Color Gamut နှင့် Panel Types (IPS, VA, TN)",
      "Operating System Kernel ဆိုတာဘာလဲ",
      "Multitasking နှင့် Multithreading",
      "Virtual Memory (Page File) အကြောင်း",
      "Cache Memory (L1, L2, L3)",
      "Clock Speed (GHz) နှင့် Cores",
      "RAID Configurations Basics",
      "Dead Pixels နှင့် Monitor Care",
      "Electrostatic Discharge (ESD) Protection",
      "Cable Management အရေးကြီးပုံ",
      "Thermal Throttling ဆိုတာဘာလဲ",
      "System Recovery Options (Beginner)",
      "Open Source Software အကြောင်း",
      "Software Licenses (EULA) အခြေခံ",
      "Cloud Storage (OneDrive/Dropbox) Basics",
      "ICT Foundation အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 2,
    title: "Computer System & Windows",
    description: "Understanding operating systems and file management.",
    target: "Windows အသုံးပြုနည်း ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Windows 10/11 Interface အကြောင်း",
      "Desktop, Taskbar နှင့် Start Menu",
      "File Explorer အသုံးပြုနည်း",
      "File နှင့် Folder တည်ဆောက်နည်း",
      "Copy, Cut, Paste နှင့် Move လုပ်နည်း",
      "Rename နှင့် Delete လုပ်နည်း (Recycle Bin)",
      "Search Box ကို အသုံးပြု၍ ရှာဖွေနည်း",
      "Wallpaper နှင့် Themes ပြောင်းလဲနည်း",
      "Display Settings (Resolution, Brightness)",
      "Control Panel နှင့် Settings အခြေခံ",
      "User Account တည်ဆောက်နည်း",
      "Date နှင့် Time ပြင်ဆင်နည်း",
      "Task Manager အသုံးပြုနည်း (Basics)",
      "Disk Management (Partitioning)",
      "System Properties စစ်ဆေးနည်း",
      "Device Manager နှင့် Drivers များ",
      "Windows Updates စီမံခန့်ခွဲနည်း",
      "Program များ Uninstall လုပ်နည်း",
      "Shortcut Keys (Windows Key Combinations)",
      "Notepad နှင့် WordPad အသုံးပြုနည်း",
      "Snipping Tool (Screen Capture)",
      "Action Center နှင့် Notifications",
      "Power Options (Sleep, Hibernate)",
      "Windows Security/Defender",
      "Virtual Desktops အသုံးပြုနည်း",
      "Compressed Folders (ZIP/RAR)",
      "Command Prompt (CMD) အခြေခံ",
      "System Restore Point တည်ဆောက်နည်း",
      "BitLocker (Drive Encryption) အခြေခံ",
      "Windows Registry အခြေခံ သိကောင်းစရာ",
      "Event Viewer အသုံးပြုနည်း",
      "Group Policy Editor (gpedit.msc)",
      "System Configuration (msconfig)",
      "PowerShell အခြေခံ အသုံးပြုနည်း",
      "Environment Variables စီမံခန့်ခွဲခြင်း",
      "Disk Defragmenter နှင့် Cleanup",
      "Third-party Personalization Tools",
      "Windows Subsystem for Linux (WSL) Intro",
      "Remote Desktop Connection",
      "Startup Programs စီမံခြင်း",
      "Services.msc (Background Services)",
      "Windows God Mode ဖန်တီးနည်း",
      "Folder Options နှင့် Hidden Files",
      "File Attributes (Read-only, Hidden)",
      "Symbolic Links နှင့် Shortcuts",
      "Network Discovery နှင့် Sharing",
      "Windows Sandbox အသုံးပြုနည်း",
      "Hyper-V Visualization Setting",
      "Registry Backup နှင့် Restore",
      "Command Line Admin Tools",
      "PowerShell Scripts (Intro)",
      "Windows Hello (Biometric Login)",
      "System File Checker (SFC /scannow)",
      "DISM Command အသုံးပြုနည်း",
      "Disk Quotas စီမံခြင်း",
      "Dynamic vs Basic Disks",
      "MBR vs GPT Partition Tables",
      "Windows Boot Manager အကြောင်း",
      "Safe Mode with Networking",
      "DirectX နှင့် Runtime အကြောင်း",
      "Fonts Management (Install/Remove)",
      "Task Scheduler (Auto Tasks)",
      "Performance Monitor အသုံးပြုနည်း",
      "Resource Monitor နားလည်မှု",
      "Reliability Monitor အကြောင်း",
      "Windows Features (Turn On/Off)",
      "Fast Startup အကျိုးနှင့်အပြစ်",
      "Virtual RAM (Virtual Memory) Tuning",
      "Local Group Policy Tweaks",
      "Windows Troubleshooting အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "STEP_BY_STEP", description: "Step-by-step tutorial (Myanmar)" },
      { type: "DEEP_EXPLAIN", description: "ပိုမို နက်နဲစွာ ရှင်းပြချက် (Deep Dive)" },
      { type: "TROUBLESHOOT", description: "Error ဖြစ်ရင် အကြောင်းအရင်းနှင့် ဖြေရှင်းနည်း" }
    ]
  },
  {
    id: 3,
    title: "Internet & Email",
    description: "Connecting to the digital world safely.",
    target: "အင်တာနက်နှင့် အီးမေးလ် အသုံးပြုလိုသူများအတွက်",
    topics: [
      "Internet နှင့် World Wide Web (WWW)",
      "Browsers (Chrome, Edge, Firefox)",
      "Search Engine (Google) အသုံးပြုနည်း",
      "Advanced Google Search Techniques",
      "Internet Connection (Wi-Fi vs Ethernet)",
      "Modem နှင့် Router ကွာခြားချက်",
      "IP Address နှင့် DNS အခြေခံ",
      "URL နှင့် Website Structure",
      "Browser History, Cache နှင့် Cookies",
      "Bookmarks နှင့် Tabs စီမံခန့်ခွဲနည်း",
      "Incognito/Private Browsing",
      "Browser Extensions အသုံးပြုနည်း",
      "Email ဆိုတာဘာလဲ (Gmail အခြေခံ)",
      "Gmail Account အသစ်ဖွင့်နည်း",
      "Email ရေးသားနည်း (Compose)",
      "Attachments (File, Image) ပို့ဆောင်နည်း",
      "Email Inbox စီမံခြင်း (Labels, Folders)",
      "Spam နှင့် Junk Emails အကြောင်း",
      "Professional Email Etiquette",
      "Signature ဖန်တီးနည်း",
      "2-Step Verification (Account Security)",
      "Online Privacy နှင့် Safety Tips",
      "Social Media အခြေခံ (Facebook, LinkedIn)",
      "Cyber Bullying နှင့် Scam Awareness",
      "E-commerce နှင့် Online Shopping Safety",
      "Online Payments (KPay, Mobile Banking) Basics",
      "Video Conferencing (Zoom, Google Meet)",
      "Cloud Storage (Google Drive) အသုံးပြုနည်း",
      "Download နှင့် Upload သိကောင်းစရာများ",
      "FTP (File Transfer Protocol) အခြေခံ",
      "VPN (Virtual Private Network) အသုံးပြုခြင်း",
      "HTTP vs HTTPS (Security)",
      "Web Hosting နှင့် Domain အခြေခံ",
      "Internet of Things (IoT) ဆိုတာဘာလဲ",
      "Dark Web နှင့် Cyber Security Awareness",
      "Password Managers အသုံးပြုနည်း",
      "Public Wi-Fi အသုံးပြုရာတွင် သတိထားရန်",
      "Social Engineering နှင့် Phishing Attack",
      "Internet Speeds (Latency vs Bandwidth)",
      "Intranet vs Extranet",
      "Web Architecture အခြေခံ",
      "HTML/CSS ဆိုတာဘာလဲ (Introduction)",
      "IPv4 vs IPv6 ကွာခြားချက်",
      "DHCP နှင့် Static IP အကြောင်း",
      "Port Forwarding အခြေခံ",
      "Fiber Optic vs Broadband",
      "Satellite Internet အကြောင်း",
      "Web Cache နှင့် CDN အခြေခံ",
      "Cookies vs Session အကြောင်း",
      "Email Headers ဖတ်နည်း",
      "SMTP, IMAP, POP3 ကွာခြားချက်",
      "Email Filters နှင့် Rules တည်ဆောက်နည်း",
      "Mass Email နှင့် Newsletter Basics",
      "Web Browser Shortcut Keys",
      "Online Storage (Mega, Mediafire) Basics",
      "Sharing Files via Link (Permissions)",
      "Syncing Across Devices",
      "Internet Censorship အကြောင်း",
      "Digital Footprint စီမံခြင်း",
      "Ad-blockers အသုံးပြုခြင်း အကျိုး/အပြစ်",
      "Secure Shell (SSH) အခြေခံ",
      "Proxy Servers အကြောင်း",
      "Malvertising Awareness",
      "Internet Addiction နှင့် Wellbeing",
      "Internet Speed Test Tools",
      "Tethering နှင့် Hotspot အသုံးပြုနည်း",
      "Deep Web vs Dark Web",
      "BitTorrent အခြေခံ နားလည်မှု",
      "Open Source Intelligence (OSINT) Intro",
      "Internet အနှစ်ချုပ်နှင့် Future Trends"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Real-life Example Lesson" },
      { type: "DEEP_EXPLAIN", description: "နည်းပညာ အသေးစိတ် ရှင်းပြချက်" },
      { type: "TEMPLATE", description: "Email writing sample Auto Generate" }
    ]
  },
  {
    id: 4,
    title: "Microsoft Word",
    description: "Mastering professional document creation.",
    target: "စာစီစာရိုက်နှင့် ရုံးလုပ်ငန်း ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "MS Word Interface နှင့် Ribbon Overview",
      "New Document တည်ဆောက်ခြင်းနှင့် Save လုပ်နည်း",
      "Font Formatting (Bold, Italic, Underline)",
      "Myanmar Unicode vs Win Font သုံးစွဲနည်း",
      "Paragraph Alignment နှင့် Indentation",
      "Line Spacing နှင့် Paragraph Spacing",
      "Bullets နှင့် Numbering အသုံးပြုနည်း",
      "Borders နှင့် Shading ထည့်သွင်းနည်း",
      "Copy, Cut, Paste နှင့် Format Painter",
      "Find နှင့် Replace လုပ်နည်း",
      "Page Setup (Margins, Orientation, Size)",
      "Header နှင့် Footer ထည့်သွင်းနည်း",
      "Page Numbering (Automatic)",
      "Tables တည်ဆောက်ခြင်းနှင့် Design ပြင်ဆင်ခြင်း",
      "Images နှင့် Shapes ထည့်သွင်းနည်း",
      "SmartArt နှင့် Charts အခြေခံ",
      "Hyperlinks နှင့် Bookmarks",
      "Symbols နှင့် Equation များ",
      "Columns (Newspaper Style) ခွဲနည်း",
      "Watermark နှင့် Page Color",
      "Table of Contents (Automatic) ပြုလုပ်နည်း",
      "Mail Merge အခြေခံ (Labels, Letters)",
      "Spelling နှင့် Grammar Check",
      "Track Changes နှင့် Comments",
      "Protecting Document with Password",
      "Exporting to PDF/XPS",
      "Templates အသုံးပြု၍ စာရွက်စာတမ်း ဖန်တီးနည်း",
      "Advanced Styles နှင့် Formatting",
      "Cross-references နှင့် Captions",
      "Footnotes နှင့် Endnotes",
      "Bibliography နှင့် Citations (APA Style)",
      "Macros in Word (Basics)",
      "Customizing the Quick Access Toolbar",
      "Restrict Editing နှင့် Permissions",
      "Comparing and Merging Documents",
      "Text Box နှင့် Drop Cap အသုံးပြုနည်း",
      "Envelopes နှင့် Labels Printing",
      "Quick Parts နှင့် AutoText",
      "Building Blocks Organizer",
      "Document Inspector (Metadata Remove)",
      "Accessibility Checker အသုံးပြုနည်း",
      "Navigation Pane (Headings Manage)",
      "Section Breaks (Next Page vs Continuous)",
      "Page Breaks vs Column Breaks",
      "Advanced Table Calculations",
      "Custom Margins and Gutter",
      "Thesaurus နှင့် Dictionary အသုံးပြုခြင်း",
      "Translating Text within Word",
      "Ink Annotations and Drawing",
      "Inserting Online Videos",
      "Sidebar and Pull Quote Design",
      "Creating Forms with Content Controls",
      "Developer Tab Overview",
      "XML Mapping Basics",
      "Object Linking and Embedding (OLE)",
      "Recovering Unsaved Documents",
      "PDF Reflow (Edit PDF in Word)",
      "Word Keyboard Shortcuts (Essential List)",
      "Control Key Shortcuts (Ctrl+A to Z)",
      "Function Key Shortcuts (F1 to F12)",
      "Formatting Shortcuts (Shift+Ctrl+F/P)",
      "Table Navigation Shortcuts",
      "Managing Large Documents (Master Docs)",
      "Standard CV Formatting Tips",
      "Office Letter Formatting Standard",
      "Win Font Keyboard Shortcuts in Word",
      "Unicode Typing Shortcuts in Word",
      "MS Word Mastery အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Letter / CV Template Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "ကျွမ်းကျင်နည်းလမ်းများ ရှင်းပြချက်" },
      { type: "QUIZ", description: "Exercise Question Auto Create" }
    ]
  },
  {
    id: 5,
    title: "Microsoft Excel",
    description: "Data management and basic calculations.",
    target: "စာရင်းဇယားနှင့် တွက်ချက်မှု ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Excel Interface (Cell, Row, Column)",
      "Workbooks နှင့် Worksheets အကြောင်း",
      "Data Entry နှင့် Data Types (Text, Number, Date)",
      "Cell Formatting (Font, Color, Border)",
      "Alignment နှင့် Merge Cells",
      "Number Formatting (Currency, Percentage)",
      "Basic Formulas (+, -, *, /)",
      "AutoSum (SUM, AVERAGE, COUNT, MAX, MIN)",
      "Relative vs Absolute Cell Reference ($)",
      "Fill Handle နှင့် Flash Fill အသုံးပြုနည်း",
      "Sorting Data (A-Z, Z-A)",
      "Filtering Data (Basic Filter)",
      "Conditional Formatting အခြေခံ",
      "Charts (Column, Pie, Line) တည်ဆောက်နည်း",
      "Freeze Panes နှင့် Split Window",
      "Page Layout နှင့် Printing Spreadsheet",
      "IF Function (Logical Test)",
      "VLOOKUP အခြေခံ နားလည်မှု",
      "HLOOKUP အခြေခံ",
      "Concatenate (Text Join) လုပ်နည်း",
      "Data Validation (Dropdown List)",
      "Pivot Tables (Data Analysis) Intro",
      "Named Ranges အသုံးပြုနည်း",
      "Error Types (#VALUE!, #REF!, #DIV/0!)",
      "Protecting Sheet နှင့် Workbook",
      "XLOOKUP (The Modern Lookup)",
      "INDEX and MATCH (Advanced Lookup)",
      "IFERROR and Logical Nesting",
      "Power Query အခြေခံ (Get & Transform)",
      "Advanced Pivot Charts",
      "Slicers နှင့် Timelines (Dashboards)",
      "What-If Analysis (Data Tables)",
      "Solver နှင့် Analysis ToolPak",
      "Array Formulas (Spill Functions)",
      "Excel VBA Macros (Recording)",
      "Excel Data Cleanup (Remove Duplicates)",
      "Text-to-Columns and Delimiters",
      "Importing Data from Web/API",
      "COUNTIF and SUMIF Functions",
      "AVERAGEIF and Multiple Criteria",
      "IFS and SWITCH Functions",
      "TEXTJOIN and CONCAT (Office 365)",
      "LEFT, RIGHT, MID (String Functions)",
      "FIND and SEARCH Functions",
      "DATE and TIME Calculations",
      "NETWORKDAYS and WORKDAY Functions",
      "VBA User Defined Functions (UDF)",
      "Protecting Cells while allowing Entry",
      "Data Modeling Basics",
      "Measure and Calculated Columns Intro",
      "Advanced Conditional Formatting (Formula based)",
      "Sparklines (Mini Charts)",
      "Group and Outline Data",
      "Subtotals (Automatic)",
      "Consolidating Multiple Sheets",
      "Excel Shortcuts (Navigation)",
      "Ctrl+Arrow Keys for Fast Movement",
      "Ctrl+Space and Shift+Space (Selection)",
      "Alt Key Shortcuts for Ribbon",
      "Ctrl+PageUp/Down (Sheet Switch)",
      "Paste Special (Values, Formulas, Transpose)",
      "Formula Auditing (Trace Precedents)",
      "Watch Window for Data Monitoring",
      "Custom Sort Levels",
      "Wildcards in Filter and Formulas (*, ?)",
      "Excel Data Dashboard Design",
      "Excel အနှစ်ချုပ်နှင့် Practice Tips"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Excel Practice Data Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Formula Explanation in Myanmar" }
    ]
  },
  {
    id: 6,
    title: "PowerPoint",
    description: "Creating effective presentations.",
    target: "တင်ပြမှုစွမ်းရည် တိုးတက်လိုသူများအတွက်",
    topics: [
      "PowerPoint Interface နှင့် Slide Layouts",
      "New Slide ထည့်နည်းနှင့် Slide Master Intro",
      "Themes နှင့် Background Styles",
      "Text Box အသုံးပြုခြင်းနှင့် Formatting",
      "Images နှင့် Icons ထည့်သွင်းခြင်း",
      "Shapes နှင့် SmartArt Graphics",
      "Charts နှင့် Tables ထည့်သွင်းနည်း",
      "Transitions (Slide to Slide Effects)",
      "Animations (Object Effects) အခြေခံ",
      "Animation Pane အသုံးပြုနည်း",
      "Audio နှင့် Video ထည့်သွင်းခြင်း",
      "Hyperlinks နှင့် Action Buttons",
      "Slide Show Settings (From Beginning/Current)",
      "Presenter View အသုံးပြုနည်း",
      "Record Slide Show (Voice Over)",
      "Notes Page နှင့် Handouts",
      "Design Ideas (AI Tool) အသုံးပြုနည်း",
      "Grouping နှင့် Aligning Objects",
      "Crop နှင့် Image Adjustments",
      "Eyedropper Tool နှင့် Color Schemes",
      "Printing Slides နှင့် Notes",
      "Exporting to Video (MP4)",
      "Package for CD/Flash Drive",
      "Presentation Tips (The 10/20/30 Rule)",
      "Body Language နှင့် Presentation Skills",
      "Slide Master Advanced Layouts",
      "Custom Slide Shows ဖန်တီးနည်း",
      "Embedding Excel Data in PPT",
      "Interactive Quiz ဖန်တီးနည်း (PPT)",
      "Morph Transition (Advanced Effect)",
      "3D Models နှင့် SVG Icons အသုံးပြုခြင်း",
      "Zoom Feature (Slide/Section Zoom)",
      "Ink Tools နှင့် Laser Pointer",
      "Collaborating on OneDrive",
      "Converting PPT to PDF/Images",
      "Animation Triggers (Click to show)",
      "Motion Paths (Advanced Animation)",
      "Emphasis Effects အသုံးပြုနည်း",
      "Combining Shapes (Merge Shapes)",
      "Compressing Media Files",
      "SmartArt to Shapes Conversion",
      "Slide Background Removal",
      "Photo Album Feature",
      "Using Rehearse with Coach (AI)",
      "Live Captions and Subtitles",
      "Screen Recording within PPT",
      "Hiding Slides for Different Audiences",
      "Setting up Self-Running Kiosk",
      "Using Ink to Text/Shape",
      "PowerPoint Keyboard Shortcuts",
      "F5 and Shift+F5 (Start Show)",
      "B and W keys during Slide Show",
      "Ctrl+P for Pen during Show",
      "Ctrl+M for New Slide",
      "Managing Linked Files",
      "Standard Slide Sizes (4:3 vs 16:9)",
      "Exporting Slides as High Res Images",
      "Creating Infographics in PPT",
      "Digital Signage with PowerPoint",
      "Using Add-ins for PPT",
      "Accessibility Standards for Slides",
      "Professional Branding in PPT",
      "Handling Q&A Sessions",
      "PowerPoint အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Slide Content Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Professional Skills Deep Dive" },
      { type: "STEP_BY_STEP", description: "Presentation Script Auto Generate" }
    ]
  },
  {
    id: 7,
    title: "AI for Daily Life",
    description: "Leveraging modern AI tools for productivity.",
    target: "AI ကို ထိရောက်စွာ အသုံးပြုလိုသူများအတွက်",
    topics: [
      "Artificial Intelligence (AI) ဆိုတာဘာလဲ",
      "Generative AI အကြောင်း နားလည်မှု",
      "Gemini နှင့် ChatGPT နှိုင်းယှဉ်ချက်",
      "Prompt Engineering (အခြေခံ)",
      "ထိရောက်သော Prompt ရေးသားနည်းများ",
      "AI ဖြင့် Email ရေးသားနည်း",
      "AI ကို အသုံးပြု၍ ဘာသာပြန်ဆိုခြင်း",
      "AI ဖြင့် ခရီးစဉ် (Itinerary) ရေးဆွဲခြင်း",
      "AI နှင့် သင်ယူမှု (Self-Study Helper)",
      "AI ဖြင့် Content Writing လုပ်ခြင်း",
      "AI Image Generation (DALL-E, Adobe Firefly)",
      "AI ဖြင့် Resume နှင့် CV ပြုပြင်ခြင်း",
      "AI ကို Coding အခြေခံတွင် အသုံးပြုနည်း",
      "Google Lens (AI Vision) အသုံးပြုနည်း",
      "AI Voice Assistants (Siri, Google Assistant)",
      "AI in Microsoft Office (Copilot Intro)",
      "AI for Video Editing (Descript, Runway)",
      "AI Ethics နှင့် တာဝန်ယူမှုရှိစွာ သုံးစွဲရေး",
      "Fake News နှင့် Deepfakes ခွဲခြားနည်း",
      "AI for Math and Science Problems",
      "AI နှင့် Data Privacy သိကောင်းစရာ",
      "Personal AI Tutor အဖြစ် အသုံးပြုနည်း",
      "AI ဖြင့် သတင်းအနှစ်ချုပ် (Summarization)",
      "AI in Social Media (Algorithm Basics)",
      "Claude နှင့် Perplexity AI အခြေခံ",
      "AI Agent ဆိုတာဘာလဲ (Intro)",
      "Custom GPTs တည်ဆောက်နည်း",
      "AI ဖြင့် Music Generation (Suno/Udio)",
      "AI Browser Extensions (Monica/Harpa)",
      "Automation with Zapier and AI",
      "Midjourney for Professional Art",
      "AI for Language Learning (Duolingo/AI)",
      "AI Video Avatars (HeyGen/Synthesia)",
      "AI Logo Generation",
      "Prompting for Specific Roles (Law, Med, Teach)",
      "AI Text-to-Speech (ElevenLabs)",
      "AI Meeting Assistants (Otter.ai)",
      "AI for Spreadsheet Analysis",
      "Negative Prompts in Image AI",
      "In-painting and Out-painting Basics",
      "AI for Financial Planning",
      "AI and Job Market (New Opportunities)",
      "Detecting AI Content (AI Detectors)",
      "Bias in AI Algorithms",
      "Prompt Chaining Techniques",
      "Few-shot vs Zero-shot Prompting",
      "Context Windows in LLMs",
      "Vector Databases (High Level Intro)",
      "AI Hallucinations အကြောင်း",
      "AI for Legal Research Intro",
      "AI and Mental Health Apps",
      "AI for Genealogy and History",
      "AI in E-commerce (Recommendations)",
      "Open Source LLMs (Llama, Mistral)",
      "Building a Local AI Server (Basic)",
      "AI for Travel Planning Pro",
      "AI for Scientific Research",
      "The Future of Work with AI",
      "Prompts for Different Professions",
      "AI နှင့် လူသားတို့၏ ပူးပေါင်းဆောင်ရွက်မှု",
      "AI for Daily Life အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Prompt Example Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "AI Internal Working Detail" },
      { type: "EXPLAIN", description: "Beginner-friendly Explanation" }
    ]
  },
  {
    id: 8,
    title: "Myanmar Typing",
    description: "Fast and accurate Myanmar language typing.",
    target: "မြန်မာစာရိုက် ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Myanmar Unicode Standard အကြောင်း",
      "Zawgyi နှင့် Unicode ကွာခြားချက်",
      "Pyidaungsu Keyboard Layout နားလည်မှု",
      "လက်ကွက် အခြေခံ (Finger Placement)",
      "Home Row Keys Practice",
      "Top Row Keys Practice",
      "Bottom Row Keys Practice",
      "Shift Key နှင့် အဆင့်မြင့် ဗျည်းများ",
      "သရနှင့် ဗျည်းတွဲ ရိုက်နည်းများ",
      "ဆင့်ဆင့် (Stacked Characters) ရိုက်နည်း",
      "Numbers နှင့် Symbols ရိုက်နည်း",
      "Typing Speed Test (Unicode)",
      "Win Font အသုံးပြုပုံ (Legacy System)",
      "Font Converters အသုံးပြုနည်း",
      "Myanmar Typing Shortcuts",
      "Win Font Keyboard Layout (Aung/WinInnwa)",
      "Win Font Character Mapping (Key by Key)",
      "Win Font vs Unicode Hand Placement",
      "Common Win Font Symbols (Key combinations)",
      "Win Font to Unicode Conversion Shortcuts",
      "Typing common Myanmar Honorifics",
      "Shortcuts for Myanmar Names (Quick strings)",
      "Win Font Table Formatting Layout",
      "Unicode Language Settings in Windows 11",
      "Gboard Myanmar Layout (Mobile)",
      "Keyman Keyboard Configuration",
      "Myanmar Language Pack for Office",
      "Typing complex Pali strings (Shortcuts)",
      "AltGr + Key combinations for Unicode",
      "Myanmar Zero (၀) vs English Zero (0)",
      "Myanmar Letter U (ဥ) vs Letter O (ဝ)",
      "Myanmar Letter Wa (ဝ) vs Zero (၀)",
      "Smart Quotes in Myanmar Typing",
      "Keyboard Heatmap for Myanmar Typing",
      "Accuracy vs Speed Training Drills",
      "Blind Typing Myanmar Practice",
      "Win Font Layout: Top Row Shifted",
      "Win Font Layout: Bottom Row Keys",
      "Win Font Layout: Consonant Stackers",
      "Win Font Layout: Medials (Ya-pin, etc.)",
      "Shortcuts for common Myanmar Suffixes",
      "Office standard Myanmar font sizes",
      "Myanmar Font Rendering Issues Fix",
      "Legacy document repair (Win Font)",
      "OCR for Myanmar Win Font Docs",
      "Myanmar Digital Content Standards",
      "Typography in Myanmar Design",
      "Typing Speed Competitions (Intro)",
      "Keyboard Ergonomics for Fast Typing",
      "Standardizing Myanmar Documents",
      "Advanced Key Combinations (AltGr)",
      "Win Font Typing Accuracy Drills",
      "Win Font vs Unicode Side-by-Side",
      "Myanmar Typing အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Typing Practice Text Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Keyboard Layout Details" },
      { type: "TROUBLESHOOT", description: "Error correction suggestion" }
    ]
  },
  {
    id: 9,
    title: "Computer Error & Fixing",
    description: "Basic troubleshooting and hardware maintenance.",
    target: "ကွန်ပျူတာ ပြဿနာများကို ကိုယ်တိုင်ဖြေရှင်းလိုသူများအတွက်",
    topics: [
      "Troubleshooting Methodology (အခြေခံ)",
      "Computer မတက်ခြင်း (No Power) ဖြေရှင်းနည်း",
      "Blue Screen of Death (BSOD) အကြောင်း",
      "Windows Slow ဖြစ်ခြင်းကို ဖြေရှင်းနည်း",
      "Internet Connection ပြဿနာများ",
      "Wi-Fi မချိတ်ဆက်နိုင်ခြင်း",
      "USB Drive မပေါ်ခြင်း (Not Recognized)",
      "Keyboard နှင့် Mouse အလုပ်မလုပ်ခြင်း",
      "Audio/Sound ပြဿနာများ",
      "Printer မထွက်ခြင်း (Offline/Error)",
      "Software Hang/Freeze ဖြစ်ခြင်း",
      "Computer Overheating ပြဿနာ",
      "Virus/Malware ကူးစက်ခံရခြင်း လက္ခဏာများ",
      "Malware ဖယ်ရှားနည်း (Manual vs Auto)",
      "System Recovery Options",
      "Safe Mode သို့ ဝင်ရောက်နည်း",
      "Driver Update လုပ်နည်း",
      "Task Manager ဖြင့် Performance စစ်ဆေးနည်း",
      "Disk Cleanup နှင့် Defragmentation",
      "RAM စစ်ဆေးခြင်းနှင့် သန့်ရှင်းရေး",
      "Hard Disk Health (S.M.A.R.T) စစ်ဆေးနည်း",
      "Battery Life နှင့် Maintenance",
      "Windows Activation Errors",
      "Application Error Codes ဖြေရှင်းနည်း",
      "Creating Bootable USB",
      "Windows ပြန်တင်နည်း (Clean Install Intro)",
      "Data Recovery (Deleted Files)",
      "Remote Desktop/TeamViewer အခြေခံ",
      "BIOS/UEFI Settings အခြေခံ",
      "CMOS Battery Replacement",
      "Network Troubleshooting (ping, tracert)",
      "Fixing Corrupt System Files (SFC)",
      "Partition Loss Recovery",
      "Diagnosing Motherboard Beep Codes",
      "Router Reset and Configuration",
      "Hardware Component Replacement",
      "Cloud Backup for Recovery",
      "Event Viewer Error Log Reading",
      "Check Disk (chkdsk) Utility",
      "Memory Diagnostic Tool (mdsched)",
      "Safe Mode vs Clean Boot",
      "Advanced Startup Options",
      "Power Supply Testing (Basic)",
      "GPU Artifacts and Fixing",
      "Thermal Paste Replacement Guide",
      "Cleaning Sticky Keyboards",
      "Fixing Flickering Monitors",
      "Data Recovery with Recuva/PhotoRec",
      "Windows Registry Repair",
      "Malwarebytes and Defender Scan pro",
      "Ransomware Protection Basics",
      "Fixing Audio Jack Problems",
      "Webcam not working fix",
      "Bluetooth Pairing Issues",
      "Updating BIOS Safely",
      "Resolving Driver Conflicts",
      "Uninstalling Stubborn Apps",
      "Fixing Windows Store Errors",
      "Restoring System Image",
      "Hardware Upgrade Paths (RAM/SSD)",
      "Diagnosing PSU Failure",
      "Troubleshooting Port Failures",
      "Cable Replacement vs Repair",
      "Hardware Maintenance Checklist"
    ],
    aiFeatures: [
      { type: "TROUBLESHOOT", description: "Error Input → Solution Auto Show" },
      { type: "DEEP_EXPLAIN", description: "Technical Fix Explained" },
      { type: "STEP_BY_STEP", description: "Beginner-friendly Fix Steps" }
    ]
  },
  {
    id: 10,
    title: "Windows OS Mastery",
    description: "Complete mastery of Windows operating system.",
    target: "Windows အထူးကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Windows 11 Advanced Features",
      "PowerShell Scripting Mastery",
      "Windows Server Basics",
      "Active Directory Fundamentals",
      "Group Policy Advanced Management",
      "Windows Registry Deep Dive",
      "Windows Security Hardening",
      "Windows Performance Tuning",
      "Windows Troubleshooting Advanced",
      "Windows Deployment Tools",
      "Windows Update Management",
      "Windows Networking Advanced",
      "Windows Storage Spaces",
      "Windows Virtualization (Hyper-V)",
      "Windows Containers and WSL2",
      "Windows Remote Management",
      "Windows Event Logging Analysis",
      "Windows Backup and Recovery Pro",
      "Windows Firewall Configuration",
      "Windows Defender Advanced Settings",
      "BitLocker Drive Encryption",
      "Windows Hello for Business",
      "Windows Credential Manager",
      "Windows Task Scheduler Advanced",
      "Windows Services Management",
      "Windows Disk Management Pro",
      "Windows File System (NTFS, ReFS)",
      "Windows User Account Control (UAC)",
      "Windows App Compatibility",
      "Windows System Restore Advanced",
      "Windows Memory Management",
      "Windows Process Management",
      "Windows Thread Management",
      "Windows Kernel Architecture",
      "Windows Boot Process Deep Dive",
      "Windows Shutdown and Hibernate",
      "Windows Sleep States",
      "Windows Power Management",
      "Windows Device Drivers Deep",
      "Windows Hardware Abstraction Layer",
      "Windows API Programming Basics",
      "Windows COM and DCOM",
      "Windows WMI (Windows Management Instrumentation)",
      "Windows Event Tracing (ETW)",
      "Windows Performance Counters",
      "Windows Resource Monitor Advanced",
      "Windows Reliability Monitor",
      "Windows System Information Tool",
      "Windows Command Line Tools Advanced",
      "Windows Batch Scripting",
      "Windows VBScript Basics",
      "Windows JScript Basics",
      "Windows .NET Framework Integration",
      "Windows Runtime (WinRT)",
      "Windows Universal Windows Platform (UWP)",
      "Windows Store Apps Management",
      "Windows Sandbox Advanced",
      "Windows Subsystem for Android",
      "Windows Game Mode and Optimization",
      "Windows OS Mastery Summary"
    ],
    aiFeatures: [
      { type: "STEP_BY_STEP", description: "Advanced Windows Configuration Steps" },
      { type: "DEEP_EXPLAIN", description: "Windows Internal Architecture Details" },
      { type: "TROUBLESHOOT", description: "Complex Windows Error Resolution" }
    ]
  },
  {
    id: 11,
    title: "Digital Skills for Work & Business",
    description: "အလုပ်လုပ်ရာမှာ တကယ်အသုံးချရမယ့် Digital Skill များ",
    target: "အလုပ်လုပ်ငန်းများတွင် ဒစ်ဂျစ်တယ် ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Google Drive (Docs, Sheets, Slides)",
      "Cloud Storage Concept",
      "Online Form (Google Form)",
      "Basic Online Collaboration",
      "File Sharing & Permission Control",
      "Microsoft Teams အခြေခံ",
      "Zoom Meeting စီမံခန့်ခွဲခြင်း",
      "Video Conferencing Etiquette",
      "Online Meeting Recording",
      "Screen Sharing နည်းလမ်းများ",
      "Virtual Backgrounds အသုံးပြုခြင်း",
      "Meeting Invitations ပို့ဆောင်ခြင်း",
      "Calendar Scheduling (Outlook/Google)",
      "Time Zone Management",
      "Meeting Minutes ရေးသားခြင်း",
      "Project Management Tools (Trello, Asana)",
      "Task Assignment နှင့် Tracking",
      "Deadline Setting နည်းလမ်းများ",
      "Workflow Automation (Zapier)",
      "Email Templates တည်ဆောက်ခြင်း",
      "Professional Email Signatures",
      "Email Filters နှင့် Rules",
      "Spam Management",
      "Email Encryption Basics",
      "Digital Signatures",
      "Document Version Control",
      "File Naming Conventions",
      "Cloud Backup Strategies",
      "Data Synchronization",
      "Offline Access စီမံခန့်ခွဲခြင်း",
      "Google Workspace vs Microsoft 365",
      "Collaborative Document Editing",
      "Commenting and Suggestions",
      "Track Changes in Documents",
      "Review and Approval Processes",
      "Digital Contracts အခြေခံ",
      "E-signature Tools (DocuSign)",
      "Legal Document Templates",
      "Invoice Creation နည်းလမ်းများ",
      "Expense Tracking Apps",
      "Budget Planning Tools",
      "Financial Reporting Basics",
      "CRM Software Introduction",
      "Customer Data Management",
      "Lead Generation Online",
      "Social Media Marketing Basics",
      "Content Calendar Planning",
      "Brand Guidelines Digital",
      "Logo Design Tools",
      "Business Card Templates",
      "Presentation Design Principles",
      "Data Visualization (Charts/Graphs)",
      "Infographic Creation",
      "Video Editing Basics",
      "Podcast Production Intro",
      "Live Streaming Setup",
      "Webinar Hosting",
      "E-commerce Platforms",
      "Online Store Setup",
      "Payment Gateway Integration",
      "Inventory Management Digital",
      "Customer Service Chatbots",
      "Help Desk Software",
      "Ticketing Systems",
      "Knowledge Base Creation",
      "Remote Work Tools",
      "VPN for Business",
      "Cybersecurity Awareness",
      "Password Management Enterprise",
      "Two-Factor Authentication",
      "Data Privacy Regulations (GDPR)",
      "Compliance Training Basics",
      "Digital Accessibility Standards",
      "Website Building Tools",
      "SEO Fundamentals",
      "Analytics Tracking",
      "Social Media Analytics",
      "Email Marketing Campaigns",
      "Newsletter Design",
      "A/B Testing for Marketing",
      "Lead Magnets Creation",
      "Sales Funnel Design",
      "Customer Journey Mapping",
      "Business Intelligence Tools",
      "Data Analysis for Business",
      "Dashboard Creation",
      "Reporting Automation",
      "Cloud Computing for Business",
      "SaaS vs PaaS vs IaaS",
      "Cost Optimization Cloud",
      "Digital Transformation Strategy",
      "Innovation in Digital Business",
      "Future of Work Trends",
      "Digital Skills for Work & Business Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 12,
    title: "AI + Automation (Advanced)",
    description: "AI ကို အလုပ်တွေနဲ့ ချိတ်ဆက်အသုံးချခြင်း",
    target: "AI နှင့် Automation ကို အလုပ်တွင် အသုံးချလိုသူများအတွက်",
    topics: [
      "AI for Office Automation",
      "Prompt Engineering Advanced",
      "AI + Excel / Docs",
      "No-Code Tools",
      "AI Ethics & Safety",
      "AI Workflow Integration",
      "Automated Report Generation",
      "Intelligent Document Processing",
      "AI-Powered Data Analysis",
      "Machine Learning for Business",
      "Natural Language Processing Applications",
      "Computer Vision in Business",
      "Robotic Process Automation (RPA)",
      "Chatbot Development for Business",
      "AI Customer Service Solutions",
      "Predictive Analytics Implementation",
      "AI-Driven Decision Making",
      "Automated Marketing Campaigns",
      "Personalized Content Generation",
      "AI Content Moderation",
      "Voice AI Assistants",
      "AI Translation Services",
      "Automated Scheduling Systems",
      "Smart Calendar Management",
      "AI Meeting Summarization",
      "Automated Email Processing",
      "Intelligent Spam Filtering",
      "AI Document Classification",
      "Automated Invoice Processing",
      "AI Contract Analysis",
      "Legal Document AI Review",
      "AI Financial Forecasting",
      "Automated Budget Tracking",
      "AI Fraud Detection",
      "Risk Assessment Automation",
      "AI Supply Chain Optimization",
      "Inventory Prediction Models",
      "AI Quality Control",
      "Automated Testing Frameworks",
      "AI Code Generation",
      "Low-Code Development Platforms",
      "API Integration Automation",
      "Workflow Orchestration",
      "Event-Driven Automation",
      "AI Monitoring and Alerting",
      "Performance Analytics Automation",
      "AI Anomaly Detection",
      "Automated Backup Systems",
      "AI Security Monitoring",
      "Threat Intelligence Automation",
      "AI Compliance Monitoring",
      "Automated Audit Trails",
      "AI Training Data Management",
      "Model Deployment Automation",
      "AI Model Monitoring",
      "Version Control for AI Models",
      "AI Bias Detection and Mitigation",
      "Ethical AI Implementation",
      "AI Transparency Frameworks",
      "Responsible AI Governance",
      "AI Safety Protocols",
      "Human-AI Collaboration Models",
      "AI Skill Development",
      "Automation Career Paths",
      "Future of AI in Business",
      "AI + Automation Summary"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Prompt Example Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "AI Internal Working Detail" },
      { type: "EXPLAIN", description: "Beginner-friendly Explanation" }
    ]
  },
  {
    id: 13,
    title: "Social Media & Online Safety",
    description: "Social Media ကို ထိရောက်ပြီး လုံခြုံစွာ အသုံးချနိုင်ဖို့",
    target: "Social Media နှင့် Online Safety ကို လေ့လာလိုသူများအတွက်",
    topics: [
      "Facebook Page / Profile Professional Setup",
      "Content Posting Strategy",
      "Basic Graphic Tools (Canva)",
      "Online Scam & Phishing Protection",
      "Privacy & Account Security",
      "Social Media Platform Overview",
      "LinkedIn Professional Networking",
      "Twitter/X for Business Communication",
      "Instagram Business Account Setup",
      "TikTok Content Creation",
      "YouTube Channel Management",
      "Social Media Content Calendar",
      "Hashtag Strategy and Research",
      "Social Media Analytics Basics",
      "Engagement Best Practices",
      "Community Management",
      "Social Media Advertising",
      "Facebook Ads Manager",
      "Instagram Shopping Features",
      "Influencer Marketing Basics",
      "Brand Voice and Tone",
      "Content Creation Tools",
      "Photo Editing with Mobile Apps",
      "Video Editing for Social Media",
      "Live Streaming on Social Platforms",
      "Storytelling Techniques",
      "Social Media Crisis Management",
      "Reputation Management Online",
      "Digital Footprint Awareness",
      "Password Security Best Practices",
      "Two-Factor Authentication Setup",
      "Privacy Settings on Social Media",
      "Data Privacy Laws (GDPR, CCPA)",
      "Cyberbullying Prevention",
      "Online Harassment Recognition",
      "Safe Online Shopping",
      "Digital Payment Security",
      "VPN Usage for Online Safety",
      "Antivirus and Security Software",
      "Malware Protection",
      "Phishing Email Detection",
      "Social Engineering Awareness",
      "Fake News Identification",
      "Online Identity Protection",
      "Parental Controls Setup",
      "Child Online Safety",
      "Digital Citizenship Education",
      "Ethical Social Media Use",
      "Copyright and Fair Use",
      "Image Rights and Permissions",
      "Social Media Legal Compliance",
      "Platform-Specific Policies",
      "Content Moderation Guidelines",
      "Algorithm Understanding",
      "SEO for Social Media",
      "Cross-Platform Content Strategy",
      "Social Media ROI Measurement",
      "Influencer Collaboration Ethics",
      "Brand Partnership Guidelines",
      "Social Media Automation Tools",
      "Scheduling Posts Effectively",
      "A/B Testing for Content",
      "Social Listening Tools",
      "Competitor Analysis Online",
      "Trend Spotting and Adaptation",
      "Social Media for Customer Service",
      "Chatbot Integration",
      "Social Commerce Setup",
      "E-commerce on Social Platforms",
      "User-Generated Content Management",
      "Social Media Metrics Deep Dive",
      "Conversion Tracking",
      "Social Media & Online Safety Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 14,
    title: "Daily Life Use Case Learning",
    description: "နေ့စဉ်ဘဝနဲ့ ချိတ်ပြီး သင်ခြင်း",
    target: "နေ့စဉ်ဘဝတွင် တကယ်ဖြစ်နိုင်သော နည်းပညာပြဿနာများကို ဖြေရှင်းနည်းလမ်းများကို လေ့လာလိုသူများအတွက်",
    topics: [
      "USB ပျောက်သွားရင် ဘာလုပ်မလဲ",
      "Email မဝင်ရင် ဘယ်လိုဖြေရှင်းမလဲ",
      "Facebook Account Hack မဖြစ်အောင်",
      "ဖုန်းလုသွားရင် ဘာလုပ်မလဲ",
      "Internet နှေးတာ ပြင်နည်း",
      "Wi-Fi Password မေ့သွားရင်",
      "File ပျက်သွားရင် ပြန်ရနည်း",
      "Printer အလုပ်မလုပ်ရင်",
      "Computer ရပ်သွားရင် Data ကယ်နည်း",
      "Phone လောင်သွားရင် ဘာလုပ်မလဲ",
      "Screen Lock မေ့သွားရင်",
      "App တွေ Crash ဖြစ်ရင်",
      "Update လုပ်ပြီး ပြဿနာဖြစ်ရင်",
      "Battery မြန်ဆင်းရင်",
      "Storage ပြည့်သွားရင်",
      "Bluetooth မချိတ်ဆက်နိုင်ရင်",
      "Speaker အသံမထွက်ရင်",
      "Keyboard အလုပ်မလုပ်ရင်",
      "Mouse အလုပ်မလုပ်ရင်",
      "Monitor မီးမထွက်ရင်",
      "USB Port အလုပ်မလုပ်ရင်",
      "Webcam အလုပ်မလုပ်ရင်",
      "Microphone အလုပ်မလုပ်ရင်",
      "Touchpad အလုပ်မလုပ်ရင်",
      "VPN မချိတ်ဆက်နိုင်ရင်",
      "Online စာတင်ရင် ဘာလိုအရင်လုပ်မလဲ",
      "Job Application Online ဖြည့်နည်း",
      "Zoom မှာ Class တက်နည်း",
      "Google Meet မှာ Meeting လုပ်နည်း",
      "Online Shopping လုပ်နည်း",
      "Online Banking အသုံးပြုနည်း",
      "Mobile Banking App သုံးနည်း",
      "Digital Payment လုပ်နည်း",
      "Credit Card နဲ့ Online ပို့နည်း",
      "E-wallet အသုံးပြုနည်း",
      "QR Code ဖတ်နည်း",
      "Google Drive မှာ File တင်နည်း",
      "Cloud Storage ကနေ Download လုပ်နည်း",
      "Google Docs မှာ စာရိုက်နည်း",
      "Google Sheets မှာ စာရင်းသွင်းနည်း",
      "Google Slides နဲ့ Presentation လုပ်နည်း",
      "Canva နဲ့ Design လုပ်နည်း",
      "YouTube မှာ Video ကြည့်နည်း",
      "Facebook မှာ Post တင်နည်း",
      "Messenger မှာ Message ပို့နည်း",
      "Viber အသုံးပြုနည်း",
      "Telegram အသုံးပြုနည်း",
      "Line App အသုံးပြုနည်း",
      "TikTok မှာ Video တင်နည်း",
      "Instagram အသုံးပြုနည်း",
      "Twitter/X အသုံးပြုနည်း",
      "LinkedIn Profile တည်ဆောက်နည်း",
      "Password Manager သုံးနည်း",
      "2FA Setup လုပ်နည်း",
      "Email Spam ကို စစ်ထုတ်နည်း",
      "Pop-up Ad တားနည်း",
      "Phone မှာ App ထည့်နည်း",
      "App Permissions စစ်ဆေးနည်း",
      "Daily Life Use Case Learning Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 15,
    title: "Basic IT Support Awareness",
    description: "IT မဟုတ်ပေမယ့် IT နားလည်စေဖို့",
    target: "IT အခြေခံကို နားလည်စေလိုသူများအတွက်",
    topics: [
      "Common Office IT Problems",
      "Software Install / Uninstall",
      "Driver Concept (Printer, USB)",
      "Virus & Antivirus (Beginner)",
      "When to Call IT Technician",
      "Printer Not Responding Issues",
      "Computer Slow Performance",
      "Internet Connection Problems",
      "Email Not Working",
      "Password Reset Procedures",
      "Account Lockout Resolution",
      "Screen Display Issues",
      "Audio Not Working",
      "USB Device Not Recognized",
      "Keyboard/Mouse Problems",
      "Software Crashing",
      "Application Not Opening",
      "Windows Update Issues",
      "Blue Screen Errors",
      "Battery and Power Issues",
      "Overheating Problems",
      "Data Backup Basics",
      "File Recovery Methods",
      "Network Cable Issues",
      "Wi-Fi Connection Drops",
      "VPN Connection Problems",
      "Remote Access Setup",
      "Firewall Settings Basics",
      "Antivirus Scan Procedures",
      "Malware Removal Steps",
      "Phishing Email Identification",
      "Suspicious Link Detection",
      "Safe Browsing Practices",
      "Password Management",
      "Two-Factor Authentication",
      "Data Privacy Basics",
      "Confidential Information Handling",
      "Physical Security Awareness",
      "Cable Management Basics",
      "Hardware Inventory Basics",
      "Software License Compliance",
      "Operating System Basics",
      "File Explorer Navigation",
      "Folder Organization",
      "Cloud Storage Usage",
      "Document Version Control",
      "Printing Troubleshooting",
      "Scanning Documents",
      "Video Conferencing Basics",
      "Presentation Equipment",
      "Mobile Device Management",
      "BYOD Policy Basics",
      "Ticketing System Usage",
      "IT Support Request Process",
      "Escalation Procedures",
      "Documentation Requirements",
      "Change Management Basics",
      "Incident Reporting",
      "Service Request Fulfillment",
      "Basic Hardware Maintenance",
      "Cleaning and Care Guidelines",
      "Basic IT Support Awareness Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "TROUBLESHOOT", description: "Simple Troubleshooting Guide Auto Generate" }
    ]
  },
  {
    id: 16,
    title: "IT Career & Freelancing",
    description: "သင်ထားတဲ့ Skill ကို ငွေဖြစ်အောင် ပြောင်းခြင်း",
    target: "IT Career နှင့် Freelancing ကို စလိုလိုသူများအတွက်",
    topics: [
      "IT Career Paths Overview",
      "Freelancing Platforms",
      "Portfolio Building",
      "CV for IT Jobs",
      "Interview Preparation",
      "Resume Writing Tips",
      "LinkedIn Profile Optimization",
      "GitHub Profile Setup",
      "Personal Website Creation",
      "Online Presence Management",
      "Professional Networking",
      "Industry Certifications",
      "Skill Assessment and Gap Analysis",
      "Setting Career Goals",
      "Job Search Strategies",
      "Company Research",
      "Salary Negotiation",
      "Work-Life Balance",
      "Remote Work Setup",
      "Time Management",
      "Productivity Tools",
      "Communication Skills",
      "Team Collaboration",
      "Project Management Basics",
      "Agile Methodology Intro",
      "Scrum Basics",
      "Business Communication",
      "Client Management",
      "Contract Writing",
      "Invoicing Basics",
      "Tax Planning for Freelancers",
      "Financial Literacy",
      "Pricing Strategies",
      "Pitching Services",
      "Proposal Writing",
      "Client Acquisition",
      "Retainer Agreements",
      "Building Long-term Clients",
      "Testimonials and References",
      "Personal Branding",
      "Marketing Yourself",
      "Social Media for Business",
      "Content Marketing",
      "Email Outreach",
      "Cold Calling Basics",
      "Networking Events",
      "Conferences and Meetups",
      "Online Courses Creation",
      "Passive Income Streams",
      "Side Projects",
      "App Development",
      "Web Development",
      "Data Analysis Services",
      "Consulting Services",
      "Technical Writing",
      "Translation Services",
      "Graphic Design Services",
      "Video Editing Services",
      "Virtual Assistant Services",
      "Customer Support Services",
      "IT Career & Freelancing Summary"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "CV/Resume Template Auto Generate" },
      { type: "EXPLAIN", description: "Career Advice in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Freelancing Strategies Deep Dive" }
    ]
  }
];
