
import { Level } from './types';

export const CURRICULUM: Level[] = [
  {
    id: 1,
    title: "ICT FOUNDATION (Beginner)",
    description: "Building the basic foundation of computing for absolute beginners.",
    target: "ကွန်ပျူတာ မသိသေးသူများအတွက်",
    topics: [
      "Computer ဆိုတာဘာလဲ (Introduction)",
      "Hardware နှင့် Software ကွာခြားချက်",
      "Input Devices (Keyboard, Mouse, Scanner)",
      "Output Devices (Monitor, Printer, Speaker)",
      "System Unit နှင့် CPU အကြောင်း",
      "RAM နှင့် Storage (HDD/SSD) ကွာခြားချက်",
      "Laptop နှင့် Desktop ရွေးချယ်နည်း",
      "Computer စနစ်တကျ ဖွင့်နည်း/ပိတ်နည်း",
      "Mouse အသုံးပြုနည်း (Click, Double Click, Drag)",
      "Keyboard Layout နှင့် Function Keys များ",
      "Operating System (Windows) အခြေခံ",
      "Bit နှင့် Byte (Data Units) အကြောင်း",
      "Computer Ports များ (USB, HDMI, VGA)",
      "Power Supply နှင့် UPS အကြောင်း",
      "Motherboard အခြေခံ နားလည်မှု",
      "Graphics Card (GPU) ဆိုတာဘာလဲ",
      "External Storage (Pen Drive, Hard Drive)",
      "Computer Maintenance အခြေခံ",
      "Dusting နှင့် Cleaning လုပ်နည်း",
      "Ergonomics (ထိုင်ပုံထိုင်နည်း စနစ်တကျ)",
      "Computer Virus ဆိုတာဘာလဲ",
      "Antivirus အခြေခံ သိကောင်းစရာ",
      "Software Installation အခြေခံ",
      "Freeware vs Paid Software",
      "Mobile vs Computer ကွာခြားချက်",
      "Cloud Computing အခြေခံ",
      "Data Backup လုပ်ခြင်း၏ အရေးကြီးပုံ",
      "IT နယ်ပယ်ရှိ Career များ",
      "Digital Citizenship အခြေခံ",
      "BIOS Setup အခြေခံ နားလည်မှု",
      "Firmware vs Software",
      "Legacy vs UEFI Systems",
      "Computer Specs ဖတ်နည်း (Specs Reading)",
      "Overclocking အခြေခံ သိကောင်းစရာ",
      "Solid State Drive (NVMe vs SATA)",
      "Network Interface Card (NIC)",
      "Sound Card နှင့် Audio Processing",
      "Optical Drives (DVD/Blu-ray) အကြောင်း",
      "Virtualization အခြေခံ (VMware/VirtualBox)",
      "Mainframe vs Supercomputer",
      "Embedded Systems အကြောင်း",
      "Algorithm အခြေခံ နားလည်မှု",
      "Binary Number System Intro",
      "ASCII နှင့် Unicode အခြေခံ",
      "Computer History (First to Fifth Generation)",
      "Transistors နှင့် Integrated Circuits",
      "Microprocessor Evolution",
      "Motherboard Form Factors (ATX, ITX)",
      "Chipset နှင့် Bus Speed အကြောင်း",
      "Cooling Systems (Air vs Liquid)",
      "Power Supply Certification (80 Plus)",
      "Input Lag နှင့် Response Time",
      "Resolution (HD, FHD, 4K) အကြောင်း",
      "Refresh Rate (Hz) နှင့် FPS",
      "Color Gamut နှင့် Panel Types (IPS, VA, TN)",
      "Operating System Kernel ဆိုတာဘာလဲ",
      "Multitasking နှင့် Multithreading",
      "Virtual Memory (Page File) အကြောင်း",
      "Cache Memory (L1, L2, L3)",
      "Clock Speed (GHz) နှင့် Cores",
      "RAID Configurations Basics",
      "Dead Pixels နှင့် Monitor Care",
      "Electrostatic Discharge (ESD) Protection",
      "Cable Management အရေးကြီးပုံ",
      "Thermal Throttling ဆိုတာဘာလဲ",
      "System Recovery Options (Beginner)",
      "Open Source Software အကြောင်း",
      "Software Licenses (EULA) အခြေခံ",
      "Cloud Storage (OneDrive/Dropbox) Basics",
      "ICT Foundation အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 2,
    title: "Computer System & Windows",
    description: "Understanding operating systems and file management.",
    target: "Windows အသုံးပြုနည်း ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Windows 10/11 Interface အကြောင်း",
      "Desktop, Taskbar နှင့် Start Menu",
      "File Explorer အသုံးပြုနည်း",
      "File နှင့် Folder တည်ဆောက်နည်း",
      "Copy, Cut, Paste နှင့် Move လုပ်နည်း",
      "Rename နှင့် Delete လုပ်နည်း (Recycle Bin)",
      "Search Box ကို အသုံးပြု၍ ရှာဖွေနည်း",
      "Wallpaper နှင့် Themes ပြောင်းလဲနည်း",
      "Display Settings (Resolution, Brightness)",
      "Control Panel နှင့် Settings အခြေခံ",
      "User Account တည်ဆောက်နည်း",
      "Date နှင့် Time ပြင်ဆင်နည်း",
      "Task Manager အသုံးပြုနည်း (Basics)",
      "Disk Management (Partitioning)",
      "System Properties စစ်ဆေးနည်း",
      "Device Manager နှင့် Drivers များ",
      "Windows Updates စီမံခန့်ခွဲနည်း",
      "Program များ Uninstall လုပ်နည်း",
      "Shortcut Keys (Windows Key Combinations)",
      "Notepad နှင့် WordPad အသုံးပြုနည်း",
      "Snipping Tool (Screen Capture)",
      "Action Center နှင့် Notifications",
      "Power Options (Sleep, Hibernate)",
      "Windows Security/Defender",
      "Virtual Desktops အသုံးပြုနည်း",
      "Compressed Folders (ZIP/RAR)",
      "Command Prompt (CMD) အခြေခံ",
      "System Restore Point တည်ဆောက်နည်း",
      "BitLocker (Drive Encryption) အခြေခံ",
      "Windows Registry အခြေခံ သိကောင်းစရာ",
      "Event Viewer အသုံးပြုနည်း",
      "Group Policy Editor (gpedit.msc)",
      "System Configuration (msconfig)",
      "PowerShell အခြေခံ အသုံးပြုနည်း",
      "Environment Variables စီမံခန့်ခွဲခြင်း",
      "Disk Defragmenter နှင့် Cleanup",
      "Third-party Personalization Tools",
      "Windows Subsystem for Linux (WSL) Intro",
      "Remote Desktop Connection",
      "Startup Programs စီမံခြင်း",
      "Services.msc (Background Services)",
      "Windows God Mode ဖန်တီးနည်း",
      "Folder Options နှင့် Hidden Files",
      "File Attributes (Read-only, Hidden)",
      "Symbolic Links နှင့် Shortcuts",
      "Network Discovery နှင့် Sharing",
      "Windows Sandbox အသုံးပြုနည်း",
      "Hyper-V Visualization Setting",
      "Registry Backup နှင့် Restore",
      "Command Line Admin Tools",
      "PowerShell Scripts (Intro)",
      "Windows Hello (Biometric Login)",
      "System File Checker (SFC /scannow)",
      "DISM Command အသုံးပြုနည်း",
      "Disk Quotas စီမံခြင်း",
      "Dynamic vs Basic Disks",
      "MBR vs GPT Partition Tables",
      "Windows Boot Manager အကြောင်း",
      "Safe Mode with Networking",
      "DirectX နှင့် Runtime အကြောင်း",
      "Fonts Management (Install/Remove)",
      "Task Scheduler (Auto Tasks)",
      "Performance Monitor အသုံးပြုနည်း",
      "Resource Monitor နားလည်မှု",
      "Reliability Monitor အကြောင်း",
      "Windows Features (Turn On/Off)",
      "Fast Startup အကျိုးနှင့်အပြစ်",
      "Virtual RAM (Virtual Memory) Tuning",
      "Local Group Policy Tweaks",
      "Windows Troubleshooting အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "STEP_BY_STEP", description: "Step-by-step tutorial (Myanmar)" },
      { type: "DEEP_EXPLAIN", description: "ပိုမို နက်နဲစွာ ရှင်းပြချက် (Deep Dive)" },
      { type: "TROUBLESHOOT", description: "Error ဖြစ်ရင် အကြောင်းအရင်းနှင့် ဖြေရှင်းနည်း" }
    ]
  },
  {
    id: 3,
    title: "Internet & Email",
    description: "Connecting to the digital world safely.",
    target: "အင်တာနက်နှင့် အီးမေးလ် အသုံးပြုလိုသူများအတွက်",
    topics: [
      "Internet နှင့် World Wide Web (WWW)",
      "Browsers (Chrome, Edge, Firefox)",
      "Search Engine (Google) အသုံးပြုနည်း",
      "Advanced Google Search Techniques",
      "Internet Connection (Wi-Fi vs Ethernet)",
      "Modem နှင့် Router ကွာခြားချက်",
      "IP Address နှင့် DNS အခြေခံ",
      "URL နှင့် Website Structure",
      "Browser History, Cache နှင့် Cookies",
      "Bookmarks နှင့် Tabs စီမံခန့်ခွဲနည်း",
      "Incognito/Private Browsing",
      "Browser Extensions အသုံးပြုနည်း",
      "Email ဆိုတာဘာလဲ (Gmail အခြေခံ)",
      "Gmail Account အသစ်ဖွင့်နည်း",
      "Email ရေးသားနည်း (Compose)",
      "Attachments (File, Image) ပို့ဆောင်နည်း",
      "Email Inbox စီမံခြင်း (Labels, Folders)",
      "Spam နှင့် Junk Emails အကြောင်း",
      "Professional Email Etiquette",
      "Signature ဖန်တီးနည်း",
      "2-Step Verification (Account Security)",
      "Online Privacy နှင့် Safety Tips",
      "Social Media အခြေခံ (Facebook, LinkedIn)",
      "Cyber Bullying နှင့် Scam Awareness",
      "E-commerce နှင့် Online Shopping Safety",
      "Online Payments (KPay, Mobile Banking) Basics",
      "Video Conferencing (Zoom, Google Meet)",
      "Cloud Storage (Google Drive) အသုံးပြုနည်း",
      "Download နှင့် Upload သိကောင်းစရာများ",
      "FTP (File Transfer Protocol) အခြေခံ",
      "VPN (Virtual Private Network) အသုံးပြုခြင်း",
      "HTTP vs HTTPS (Security)",
      "Web Hosting နှင့် Domain အခြေခံ",
      "Internet of Things (IoT) ဆိုတာဘာလဲ",
      "Dark Web နှင့် Cyber Security Awareness",
      "Password Managers အသုံးပြုနည်း",
      "Public Wi-Fi အသုံးပြုရာတွင် သတိထားရန်",
      "Social Engineering နှင့် Phishing Attack",
      "Internet Speeds (Latency vs Bandwidth)",
      "Intranet vs Extranet",
      "Web Architecture အခြေခံ",
      "HTML/CSS ဆိုတာဘာလဲ (Introduction)",
      "IPv4 vs IPv6 ကွာခြားချက်",
      "DHCP နှင့် Static IP အကြောင်း",
      "Port Forwarding အခြေခံ",
      "Fiber Optic vs Broadband",
      "Satellite Internet အကြောင်း",
      "Web Cache နှင့် CDN အခြေခံ",
      "Cookies vs Session အကြောင်း",
      "Email Headers ဖတ်နည်း",
      "SMTP, IMAP, POP3 ကွာခြားချက်",
      "Email Filters နှင့် Rules တည်ဆောက်နည်း",
      "Mass Email နှင့် Newsletter Basics",
      "Web Browser Shortcut Keys",
      "Online Storage (Mega, Mediafire) Basics",
      "Sharing Files via Link (Permissions)",
      "Syncing Across Devices",
      "Internet Censorship အကြောင်း",
      "Digital Footprint စီမံခြင်း",
      "Ad-blockers အသုံးပြုခြင်း အကျိုး/အပြစ်",
      "Secure Shell (SSH) အခြေခံ",
      "Proxy Servers အကြောင်း",
      "Malvertising Awareness",
      "Internet Addiction နှင့် Wellbeing",
      "Internet Speed Test Tools",
      "Tethering နှင့် Hotspot အသုံးပြုနည်း",
      "Deep Web vs Dark Web",
      "BitTorrent အခြေခံ နားလည်မှု",
      "Open Source Intelligence (OSINT) Intro",
      "Internet အနှစ်ချုပ်နှင့် Future Trends"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Real-life Example Lesson" },
      { type: "DEEP_EXPLAIN", description: "နည်းပညာ အသေးစိတ် ရှင်းပြချက်" },
      { type: "TEMPLATE", description: "Email writing sample Auto Generate" }
    ]
  },
  {
    id: 4,
    title: "Microsoft Word",
    description: "Mastering professional document creation.",
    target: "စာစီစာရိုက်နှင့် ရုံးလုပ်ငန်း ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "MS Word Interface နှင့် Ribbon Overview",
      "New Document တည်ဆောက်ခြင်းနှင့် Save လုပ်နည်း",
      "Font Formatting (Bold, Italic, Underline)",
      "Myanmar Unicode vs Win Font သုံးစွဲနည်း",
      "Paragraph Alignment နှင့် Indentation",
      "Line Spacing နှင့် Paragraph Spacing",
      "Bullets နှင့် Numbering အသုံးပြုနည်း",
      "Borders နှင့် Shading ထည့်သွင်းနည်း",
      "Copy, Cut, Paste နှင့် Format Painter",
      "Find နှင့် Replace လုပ်နည်း",
      "Page Setup (Margins, Orientation, Size)",
      "Header နှင့် Footer ထည့်သွင်းနည်း",
      "Page Numbering (Automatic)",
      "Tables တည်ဆောက်ခြင်းနှင့် Design ပြင်ဆင်ခြင်း",
      "Images နှင့် Shapes ထည့်သွင်းနည်း",
      "SmartArt နှင့် Charts အခြေခံ",
      "Hyperlinks နှင့် Bookmarks",
      "Symbols နှင့် Equation များ",
      "Columns (Newspaper Style) ခွဲနည်း",
      "Watermark နှင့် Page Color",
      "Table of Contents (Automatic) ပြုလုပ်နည်း",
      "Mail Merge အခြေခံ (Labels, Letters)",
      "Spelling နှင့် Grammar Check",
      "Track Changes နှင့် Comments",
      "Protecting Document with Password",
      "Exporting to PDF/XPS",
      "Templates အသုံးပြု၍ စာရွက်စာတမ်း ဖန်တီးနည်း",
      "Advanced Styles နှင့် Formatting",
      "Cross-references နှင့် Captions",
      "Footnotes နှင့် Endnotes",
      "Bibliography နှင့် Citations (APA Style)",
      "Macros in Word (Basics)",
      "Customizing the Quick Access Toolbar",
      "Restrict Editing နှင့် Permissions",
      "Comparing and Merging Documents",
      "Text Box နှင့် Drop Cap အသုံးပြုနည်း",
      "Envelopes နှင့် Labels Printing",
      "Quick Parts နှင့် AutoText",
      "Building Blocks Organizer",
      "Document Inspector (Metadata Remove)",
      "Accessibility Checker အသုံးပြုနည်း",
      "Navigation Pane (Headings Manage)",
      "Section Breaks (Next Page vs Continuous)",
      "Page Breaks vs Column Breaks",
      "Advanced Table Calculations",
      "Custom Margins and Gutter",
      "Thesaurus နှင့် Dictionary အသုံးပြုခြင်း",
      "Translating Text within Word",
      "Ink Annotations and Drawing",
      "Inserting Online Videos",
      "Sidebar and Pull Quote Design",
      "Creating Forms with Content Controls",
      "Developer Tab Overview",
      "XML Mapping Basics",
      "Object Linking and Embedding (OLE)",
      "Recovering Unsaved Documents",
      "PDF Reflow (Edit PDF in Word)",
      "Word Keyboard Shortcuts (Essential List)",
      "Control Key Shortcuts (Ctrl+A to Z)",
      "Function Key Shortcuts (F1 to F12)",
      "Formatting Shortcuts (Shift+Ctrl+F/P)",
      "Table Navigation Shortcuts",
      "Managing Large Documents (Master Docs)",
      "Standard CV Formatting Tips",
      "Office Letter Formatting Standard",
      "Win Font Keyboard Shortcuts in Word",
      "Unicode Typing Shortcuts in Word",
      "MS Word Mastery အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Letter / CV Template Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "ကျွမ်းကျင်နည်းလမ်းများ ရှင်းပြချက်" },
      { type: "QUIZ", description: "Exercise Question Auto Create" }
    ]
  },
  {
    id: 5,
    title: "Microsoft Excel",
    description: "Data management and basic calculations.",
    target: "စာရင်းဇယားနှင့် တွက်ချက်မှု ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Excel Interface (Cell, Row, Column)",
      "Workbooks နှင့် Worksheets အကြောင်း",
      "Data Entry နှင့် Data Types (Text, Number, Date)",
      "Cell Formatting (Font, Color, Border)",
      "Alignment နှင့် Merge Cells",
      "Number Formatting (Currency, Percentage)",
      "Basic Formulas (+, -, *, /)",
      "AutoSum (SUM, AVERAGE, COUNT, MAX, MIN)",
      "Relative vs Absolute Cell Reference ($)",
      "Fill Handle နှင့် Flash Fill အသုံးပြုနည်း",
      "Sorting Data (A-Z, Z-A)",
      "Filtering Data (Basic Filter)",
      "Conditional Formatting အခြေခံ",
      "Charts (Column, Pie, Line) တည်ဆောက်နည်း",
      "Freeze Panes နှင့် Split Window",
      "Page Layout နှင့် Printing Spreadsheet",
      "IF Function (Logical Test)",
      "VLOOKUP အခြေခံ နားလည်မှု",
      "HLOOKUP အခြေခံ",
      "Concatenate (Text Join) လုပ်နည်း",
      "Data Validation (Dropdown List)",
      "Pivot Tables (Data Analysis) Intro",
      "Named Ranges အသုံးပြုနည်း",
      "Error Types (#VALUE!, #REF!, #DIV/0!)",
      "Protecting Sheet နှင့် Workbook",
      "XLOOKUP (The Modern Lookup)",
      "INDEX and MATCH (Advanced Lookup)",
      "IFERROR and Logical Nesting",
      "Power Query အခြေခံ (Get & Transform)",
      "Advanced Pivot Charts",
      "Slicers နှင့် Timelines (Dashboards)",
      "What-If Analysis (Data Tables)",
      "Solver နှင့် Analysis ToolPak",
      "Array Formulas (Spill Functions)",
      "Excel VBA Macros (Recording)",
      "Excel Data Cleanup (Remove Duplicates)",
      "Text-to-Columns and Delimiters",
      "Importing Data from Web/API",
      "COUNTIF and SUMIF Functions",
      "AVERAGEIF and Multiple Criteria",
      "IFS and SWITCH Functions",
      "TEXTJOIN and CONCAT (Office 365)",
      "LEFT, RIGHT, MID (String Functions)",
      "FIND and SEARCH Functions",
      "DATE and TIME Calculations",
      "NETWORKDAYS and WORKDAY Functions",
      "VBA User Defined Functions (UDF)",
      "Protecting Cells while allowing Entry",
      "Data Modeling Basics",
      "Measure and Calculated Columns Intro",
      "Advanced Conditional Formatting (Formula based)",
      "Sparklines (Mini Charts)",
      "Group and Outline Data",
      "Subtotals (Automatic)",
      "Consolidating Multiple Sheets",
      "Excel Shortcuts (Navigation)",
      "Ctrl+Arrow Keys for Fast Movement",
      "Ctrl+Space and Shift+Space (Selection)",
      "Alt Key Shortcuts for Ribbon",
      "Ctrl+PageUp/Down (Sheet Switch)",
      "Paste Special (Values, Formulas, Transpose)",
      "Formula Auditing (Trace Precedents)",
      "Watch Window for Data Monitoring",
      "Custom Sort Levels",
      "Wildcards in Filter and Formulas (*, ?)",
      "Excel Data Dashboard Design",
      "Excel အနှစ်ချုပ်နှင့် Practice Tips"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Excel Practice Data Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Formula Explanation in Myanmar" }
    ]
  },
  {
    id: 6,
    title: "PowerPoint",
    description: "Creating effective presentations.",
    target: "တင်ပြမှုစွမ်းရည် တိုးတက်လိုသူများအတွက်",
    topics: [
      "PowerPoint Interface နှင့် Slide Layouts",
      "New Slide ထည့်နည်းနှင့် Slide Master Intro",
      "Themes နှင့် Background Styles",
      "Text Box အသုံးပြုခြင်းနှင့် Formatting",
      "Images နှင့် Icons ထည့်သွင်းခြင်း",
      "Shapes နှင့် SmartArt Graphics",
      "Charts နှင့် Tables ထည့်သွင်းနည်း",
      "Transitions (Slide to Slide Effects)",
      "Animations (Object Effects) အခြေခံ",
      "Animation Pane အသုံးပြုနည်း",
      "Audio နှင့် Video ထည့်သွင်းခြင်း",
      "Hyperlinks နှင့် Action Buttons",
      "Slide Show Settings (From Beginning/Current)",
      "Presenter View အသုံးပြုနည်း",
      "Record Slide Show (Voice Over)",
      "Notes Page နှင့် Handouts",
      "Design Ideas (AI Tool) အသုံးပြုနည်း",
      "Grouping နှင့် Aligning Objects",
      "Crop နှင့် Image Adjustments",
      "Eyedropper Tool နှင့် Color Schemes",
      "Printing Slides နှင့် Notes",
      "Exporting to Video (MP4)",
      "Package for CD/Flash Drive",
      "Presentation Tips (The 10/20/30 Rule)",
      "Body Language နှင့် Presentation Skills",
      "Slide Master Advanced Layouts",
      "Custom Slide Shows ဖန်တီးနည်း",
      "Embedding Excel Data in PPT",
      "Interactive Quiz ဖန်တီးနည်း (PPT)",
      "Morph Transition (Advanced Effect)",
      "3D Models နှင့် SVG Icons အသုံးပြုခြင်း",
      "Zoom Feature (Slide/Section Zoom)",
      "Ink Tools နှင့် Laser Pointer",
      "Collaborating on OneDrive",
      "Converting PPT to PDF/Images",
      "Animation Triggers (Click to show)",
      "Motion Paths (Advanced Animation)",
      "Emphasis Effects အသုံးပြုနည်း",
      "Combining Shapes (Merge Shapes)",
      "Compressing Media Files",
      "SmartArt to Shapes Conversion",
      "Slide Background Removal",
      "Photo Album Feature",
      "Using Rehearse with Coach (AI)",
      "Live Captions and Subtitles",
      "Screen Recording within PPT",
      "Hiding Slides for Different Audiences",
      "Setting up Self-Running Kiosk",
      "Using Ink to Text/Shape",
      "PowerPoint Keyboard Shortcuts",
      "F5 and Shift+F5 (Start Show)",
      "B and W keys during Slide Show",
      "Ctrl+P for Pen during Show",
      "Ctrl+M for New Slide",
      "Managing Linked Files",
      "Standard Slide Sizes (4:3 vs 16:9)",
      "Exporting Slides as High Res Images",
      "Creating Infographics in PPT",
      "Digital Signage with PowerPoint",
      "Using Add-ins for PPT",
      "Accessibility Standards for Slides",
      "Professional Branding in PPT",
      "Handling Q&A Sessions",
      "PowerPoint အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Slide Content Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Professional Skills Deep Dive" },
      { type: "STEP_BY_STEP", description: "Presentation Script Auto Generate" }
    ]
  },
  {
    id: 7,
    title: "AI for Daily Life",
    description: "Leveraging modern AI tools for productivity.",
    target: "AI ကို ထိရောက်စွာ အသုံးပြုလိုသူများအတွက်",
    topics: [
      "Artificial Intelligence (AI) ဆိုတာဘာလဲ",
      "Generative AI အကြောင်း နားလည်မှု",
      "Gemini နှင့် ChatGPT နှိုင်းယှဉ်ချက်",
      "Prompt Engineering (အခြေခံ)",
      "ထိရောက်သော Prompt ရေးသားနည်းများ",
      "AI ဖြင့် Email ရေးသားနည်း",
      "AI ကို အသုံးပြု၍ ဘာသာပြန်ဆိုခြင်း",
      "AI ဖြင့် ခရီးစဉ် (Itinerary) ရေးဆွဲခြင်း",
      "AI နှင့် သင်ယူမှု (Self-Study Helper)",
      "AI ဖြင့် Content Writing လုပ်ခြင်း",
      "AI Image Generation (DALL-E, Adobe Firefly)",
      "AI ဖြင့် Resume နှင့် CV ပြုပြင်ခြင်း",
      "AI ကို Coding အခြေခံတွင် အသုံးပြုနည်း",
      "Google Lens (AI Vision) အသုံးပြုနည်း",
      "AI Voice Assistants (Siri, Google Assistant)",
      "AI in Microsoft Office (Copilot Intro)",
      "AI for Video Editing (Descript, Runway)",
      "AI Ethics နှင့် တာဝန်ယူမှုရှိစွာ သုံးစွဲရေး",
      "Fake News နှင့် Deepfakes ခွဲခြားနည်း",
      "AI for Math and Science Problems",
      "AI နှင့် Data Privacy သိကောင်းစရာ",
      "Personal AI Tutor အဖြစ် အသုံးပြုနည်း",
      "AI ဖြင့် သတင်းအနှစ်ချုပ် (Summarization)",
      "AI in Social Media (Algorithm Basics)",
      "Claude နှင့် Perplexity AI အခြေခံ",
      "AI Agent ဆိုတာဘာလဲ (Intro)",
      "Custom GPTs တည်ဆောက်နည်း",
      "AI ဖြင့် Music Generation (Suno/Udio)",
      "AI Browser Extensions (Monica/Harpa)",
      "Automation with Zapier and AI",
      "Midjourney for Professional Art",
      "AI for Language Learning (Duolingo/AI)",
      "AI Video Avatars (HeyGen/Synthesia)",
      "AI Logo Generation",
      "Prompting for Specific Roles (Law, Med, Teach)",
      "AI Text-to-Speech (ElevenLabs)",
      "AI Meeting Assistants (Otter.ai)",
      "AI for Spreadsheet Analysis",
      "Negative Prompts in Image AI",
      "In-painting and Out-painting Basics",
      "AI for Financial Planning",
      "AI and Job Market (New Opportunities)",
      "Detecting AI Content (AI Detectors)",
      "Bias in AI Algorithms",
      "Prompt Chaining Techniques",
      "Few-shot vs Zero-shot Prompting",
      "Context Windows in LLMs",
      "Vector Databases (High Level Intro)",
      "AI Hallucinations အကြောင်း",
      "AI for Legal Research Intro",
      "AI and Mental Health Apps",
      "AI for Genealogy and History",
      "AI in E-commerce (Recommendations)",
      "Open Source LLMs (Llama, Mistral)",
      "Building a Local AI Server (Basic)",
      "AI for Travel Planning Pro",
      "AI for Scientific Research",
      "The Future of Work with AI",
      "Prompts for Different Professions",
      "AI နှင့် လူသားတို့၏ ပူးပေါင်းဆောင်ရွက်မှု",
      "AI for Daily Life အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Prompt Example Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "AI Internal Working Detail" },
      { type: "EXPLAIN", description: "Beginner-friendly Explanation" }
    ]
  },
  {
    id: 8,
    title: "Myanmar Typing",
    description: "Fast and accurate Myanmar language typing.",
    target: "မြန်မာစာရိုက် ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Myanmar Unicode Standard အကြောင်း",
      "Zawgyi နှင့် Unicode ကွာခြားချက်",
      "Pyidaungsu Keyboard Layout နားလည်မှု",
      "လက်ကွက် အခြေခံ (Finger Placement)",
      "Home Row Keys Practice",
      "Top Row Keys Practice",
      "Bottom Row Keys Practice",
      "Shift Key နှင့် အဆင့်မြင့် ဗျည်းများ",
      "သရနှင့် ဗျည်းတွဲ ရိုက်နည်းများ",
      "ဆင့်ဆင့် (Stacked Characters) ရိုက်နည်း",
      "Numbers နှင့် Symbols ရိုက်နည်း",
      "Typing Speed Test (Unicode)",
      "Win Font အသုံးပြုပုံ (Legacy System)",
      "Font Converters အသုံးပြုနည်း",
      "Myanmar Typing Shortcuts",
      "Win Font Keyboard Layout (Aung/WinInnwa)",
      "Win Font Character Mapping (Key by Key)",
      "Win Font vs Unicode Hand Placement",
      "Common Win Font Symbols (Key combinations)",
      "Win Font to Unicode Conversion Shortcuts",
      "Typing common Myanmar Honorifics",
      "Shortcuts for Myanmar Names (Quick strings)",
      "Win Font Table Formatting Layout",
      "Unicode Language Settings in Windows 11",
      "Gboard Myanmar Layout (Mobile)",
      "Keyman Keyboard Configuration",
      "Myanmar Language Pack for Office",
      "Typing complex Pali strings (Shortcuts)",
      "AltGr + Key combinations for Unicode",
      "Myanmar Zero (၀) vs English Zero (0)",
      "Myanmar Letter U (ဥ) vs Letter O (ဝ)",
      "Myanmar Letter Wa (ဝ) vs Zero (၀)",
      "Smart Quotes in Myanmar Typing",
      "Keyboard Heatmap for Myanmar Typing",
      "Accuracy vs Speed Training Drills",
      "Blind Typing Myanmar Practice",
      "Win Font Layout: Top Row Shifted",
      "Win Font Layout: Bottom Row Keys",
      "Win Font Layout: Consonant Stackers",
      "Win Font Layout: Medials (Ya-pin, etc.)",
      "Shortcuts for common Myanmar Suffixes",
      "Office standard Myanmar font sizes",
      "Myanmar Font Rendering Issues Fix",
      "Legacy document repair (Win Font)",
      "OCR for Myanmar Win Font Docs",
      "Myanmar Digital Content Standards",
      "Typography in Myanmar Design",
      "Typing Speed Competitions (Intro)",
      "Keyboard Ergonomics for Fast Typing",
      "Standardizing Myanmar Documents",
      "Advanced Key Combinations (AltGr)",
      "Win Font Typing Accuracy Drills",
      "Win Font vs Unicode Side-by-Side",
      "Myanmar Typing အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Typing Practice Text Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Keyboard Layout Details" },
      { type: "TROUBLESHOOT", description: "Error correction suggestion" }
    ]
  },
  {
    id: 9,
    title: "Computer Error & Fixing",
    description: "Basic troubleshooting and hardware maintenance.",
    target: "ကွန်ပျူတာ ပြဿနာများကို ကိုယ်တိုင်ဖြေရှင်းလိုသူများအတွက်",
    topics: [
      "Troubleshooting Methodology (အခြေခံ)",
      "Computer မတက်ခြင်း (No Power) ဖြေရှင်းနည်း",
      "Blue Screen of Death (BSOD) အကြောင်း",
      "Windows Slow ဖြစ်ခြင်းကို ဖြေရှင်းနည်း",
      "Internet Connection ပြဿနာများ",
      "Wi-Fi မချိတ်ဆက်နိုင်ခြင်း",
      "USB Drive မပေါ်ခြင်း (Not Recognized)",
      "Keyboard နှင့် Mouse အလုပ်မလုပ်ခြင်း",
      "Audio/Sound ပြဿနာများ",
      "Printer မထွက်ခြင်း (Offline/Error)",
      "Software Hang/Freeze ဖြစ်ခြင်း",
      "Computer Overheating ပြဿနာ",
      "Virus/Malware ကူးစက်ခံရခြင်း လက္ခဏာများ",
      "Malware ဖယ်ရှားနည်း (Manual vs Auto)",
      "System Recovery Options",
      "Safe Mode သို့ ဝင်ရောက်နည်း",
      "Driver Update လုပ်နည်း",
      "Task Manager ဖြင့် Performance စစ်ဆေးနည်း",
      "Disk Cleanup နှင့် Defragmentation",
      "RAM စစ်ဆေးခြင်းနှင့် သန့်ရှင်းရေး",
      "Hard Disk Health (S.M.A.R.T) စစ်ဆေးနည်း",
      "Battery Life နှင့် Maintenance",
      "Windows Activation Errors",
      "Application Error Codes ဖြေရှင်းနည်း",
      "Creating Bootable USB",
      "Windows ပြန်တင်နည်း (Clean Install Intro)",
      "Data Recovery (Deleted Files)",
      "Remote Desktop/TeamViewer အခြေခံ",
      "BIOS/UEFI Settings အခြေခံ",
      "CMOS Battery Replacement",
      "Network Troubleshooting (ping, tracert)",
      "Fixing Corrupt System Files (SFC)",
      "Partition Loss Recovery",
      "Diagnosing Motherboard Beep Codes",
      "Router Reset and Configuration",
      "Hardware Component Replacement",
      "Cloud Backup for Recovery",
      "Event Viewer Error Log Reading",
      "Check Disk (chkdsk) Utility",
      "Memory Diagnostic Tool (mdsched)",
      "Safe Mode vs Clean Boot",
      "Advanced Startup Options",
      "Power Supply Testing (Basic)",
      "GPU Artifacts and Fixing",
      "Thermal Paste Replacement Guide",
      "Cleaning Sticky Keyboards",
      "Fixing Flickering Monitors",
      "Data Recovery with Recuva/PhotoRec",
      "Windows Registry Repair",
      "Malwarebytes and Defender Scan pro",
      "Ransomware Protection Basics",
      "Fixing Audio Jack Problems",
      "Webcam not working fix",
      "Bluetooth Pairing Issues",
      "Updating BIOS Safely",
      "Resolving Driver Conflicts",
      "Uninstalling Stubborn Apps",
      "Fixing Windows Store Errors",
      "Restoring System Image",
      "Hardware Upgrade Paths (RAM/SSD)",
      "Diagnosing PSU Failure",
      "Troubleshooting Port Failures",
      "Cable Replacement vs Repair",
      "Hardware Maintenance Checklist"
    ],
    aiFeatures: [
      { type: "TROUBLESHOOT", description: "Error Input → Solution Auto Show" },
      { type: "DEEP_EXPLAIN", description: "Technical Fix Explained" },
      { type: "STEP_BY_STEP", description: "Beginner-friendly Fix Steps" }
    ]
  }
];
