
import { Level } from './types';

export const CURRICULUM: Level[] = [
  {
    id: 1,
    title: "ICT FOUNDATION (Beginner)",
    description: "Building the basic foundation of computing for absolute beginners.",
    target: "ကွန်ပျူတာ မသိသေးသူများအတွက်",
    category: "Beginner",
    topics: [
      "Computer ဆိုတာဘာလဲ (Introduction)",
      "Hardware နှင့် Software ကွာခြားချက်",
      "Input Devices (Keyboard, Mouse, Scanner)",
      "Output Devices (Monitor, Printer, Speaker)",
      "System Unit နှင့် CPU အကြောင်း",
      "RAM နှင့် Storage (HDD/SSD) ကွာခြားချက်",
      "Laptop နှင့် Desktop ရွေးချယ်နည်း",
      "Computer စနစ်တကျ ဖွင့်နည်း/ပိတ်နည်း",
      "Mouse အသုံးပြုနည်း (Click, Double Click, Drag)",
      "Keyboard Layout နှင့် Function Keys များ",
      "Operating System (Windows) အခြေခံ",
      "Bit နှင့် Byte (Data Units) အကြောင်း",
      "Computer Ports များ (USB, HDMI, VGA)",
      "Power Supply နှင့် UPS အကြောင်း",
      "Motherboard အခြေခံ နားလည်မှု",
      "Graphics Card (GPU) ဆိုတာဘာလဲ",
      "External Storage (Pen Drive, Hard Drive)",
      "Computer Maintenance အခြေခံ",
      "Dusting နှင့် Cleaning လုပ်နည်း",
      "Ergonomics (ထိုင်ပုံထိုင်နည်း စနစ်တကျ)",
      "Computer Virus ဆိုတာဘာလဲ",
      "Antivirus အခြေခံ သိကောင်းစရာ",
      "Software Installation အခြေခံ",
      "Freeware vs Paid Software",
      "Mobile vs Computer ကွာခြားချက်",
      "Cloud Computing အခြေခံ",
      "Data Backup လုပ်ခြင်း၏ အရေးကြီးပုံ",
      "IT နယ်ပယ်ရှိ Career များ",
      "Digital Citizenship အခြေခံ",
      "BIOS Setup အခြေခံ နားလည်မှု",
      "Firmware vs Software",
      "Legacy vs UEFI Systems",
      "Computer Specs ဖတ်နည်း (Specs Reading)",
      "Overclocking အခြေခံ သိကောင်းစရာ",
      "Solid State Drive (NVMe vs SATA)",
      "Network Interface Card (NIC)",
      "Sound Card နှင့် Audio Processing",
      "Optical Drives (DVD/Blu-ray) အကြောင်း",
      "Virtualization အခြေခံ (VMware/VirtualBox)",
      "Mainframe vs Supercomputer",
      "Embedded Systems အကြောင်း",
      "Algorithm အခြေခံ နားလည်မှု",
      "Binary Number System Intro",
      "ASCII နှင့် Unicode အခြေခံ",
      "Computer History (First to Fifth Generation)",
      "Transistors နှင့် Integrated Circuits",
      "Microprocessor Evolution",
      "Motherboard Form Factors (ATX, ITX)",
      "Chipset နှင့် Bus Speed အကြောင်း",
      "Cooling Systems (Air vs Liquid)",
      "Power Supply Certification (80 Plus)",
      "Input Lag နှင့် Response Time",
      "Resolution (HD, FHD, 4K) အကြောင်း",
      "Refresh Rate (Hz) နှင့် FPS",
      "Color Gamut နှင့် Panel Types (IPS, VA, TN)",
      "Operating System Kernel ဆိုတာဘာလဲ",
      "Multitasking နှင့် Multithreading",
      "Virtual Memory (Page File) အကြောင်း",
      "Cache Memory (L1, L2, L3)",
      "Clock Speed (GHz) နှင့် Cores",
      "RAID Configurations Basics",
      "Dead Pixels နှင့် Monitor Care",
      "Electrostatic Discharge (ESD) Protection",
      "Cable Management အရေးကြီးပုံ",
      "Thermal Throttling ဆိုတာဘာလဲ",
      "System Recovery Options (Beginner)",
      "Open Source Software အကြောင်း",
      "Software Licenses (EULA) အခြေခံ",
      "Cloud Storage (OneDrive/Dropbox) Basics",
      "ICT Foundation အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 2,
    title: "Computer System & Windows",
    description: "Understanding operating systems and file management.",
    target: "Windows အသုံးပြုနည်း ကျွမ်းကျင်လိုသူများအတွက်",
    category: "Intermediate",
    topics: [
      "Windows 10/11 Interface အကြောင်း",
      "Desktop, Taskbar နှင့် Start Menu",
      "File Explorer အသုံးပြုနည်း",
      "File နှင့် Folder တည်ဆောက်နည်း",
      "Copy, Cut, Paste နှင့် Move လုပ်နည်း",
      "Rename နှင့် Delete လုပ်နည်း (Recycle Bin)",
      "Search Box ကို အသုံးပြု၍ ရှာဖွေနည်း",
      "Wallpaper နှင့် Themes ပြောင်းလဲနည်း",
      "Display Settings (Resolution, Brightness)",
      "Control Panel နှင့် Settings အခြေခံ",
      "User Account တည်ဆောက်နည်း",
      "Date နှင့် Time ပြင်ဆင်နည်း",
      "Task Manager အသုံးပြုနည်း (Basics)",
      "Disk Management (Partitioning)",
      "System Properties စစ်ဆေးနည်း",
      "Device Manager နှင့် Drivers များ",
      "Windows Updates စီမံခန့်ခွဲနည်း",
      "Program များ Uninstall လုပ်နည်း",
      "Shortcut Keys (Windows Key Combinations)",
      "Notepad နှင့် WordPad အသုံးပြုနည်း",
      "Snipping Tool (Screen Capture)",
      "Action Center နှင့် Notifications",
      "Power Options (Sleep, Hibernate)",
      "Windows Security/Defender",
      "Virtual Desktops အသုံးပြုနည်း",
      "Compressed Folders (ZIP/RAR)",
      "Command Prompt (CMD) အခြေခံ",
      "System Restore Point တည်ဆောက်နည်း",
      "BitLocker (Drive Encryption) အခြေခံ",
      "Windows Registry အခြေခံ သိကောင်းစရာ",
      "Event Viewer အသုံးပြုနည်း",
      "Group Policy Editor (gpedit.msc)",
      "System Configuration (msconfig)",
      "PowerShell အခြေခံ အသုံးပြုနည်း",
      "Environment Variables စီမံခန့်ခွဲခြင်း",
      "Disk Defragmenter နှင့် Cleanup",
      "Third-party Personalization Tools",
      "Windows Subsystem for Linux (WSL) Intro",
      "Remote Desktop Connection",
      "Startup Programs စီမံခြင်း",
      "Services.msc (Background Services)",
      "Windows God Mode ဖန်တီးနည်း",
      "Folder Options နှင့် Hidden Files",
      "File Attributes (Read-only, Hidden)",
      "Symbolic Links နှင့် Shortcuts",
      "Network Discovery နှင့် Sharing",
      "Windows Sandbox အသုံးပြုနည်း",
      "Hyper-V Visualization Setting",
      "Registry Backup နှင့် Restore",
      "Command Line Admin Tools",
      "PowerShell Scripts (Intro)",
      "Windows Hello (Biometric Login)",
      "System File Checker (SFC /scannow)",
      "DISM Command အသုံးပြုနည်း",
      "Disk Quotas စီမံခြင်း",
      "Dynamic vs Basic Disks",
      "MBR vs GPT Partition Tables",
      "Windows Boot Manager အကြောင်း",
      "Safe Mode with Networking",
      "DirectX နှင့် Runtime အကြောင်း",
      "Fonts Management (Install/Remove)",
      "Task Scheduler (Auto Tasks)",
      "Performance Monitor အသုံးပြုနည်း",
      "Resource Monitor နားလည်မှု",
      "Reliability Monitor အကြောင်း",
      "Windows Features (Turn On/Off)",
      "Fast Startup အကျိုးနှင့်အပြစ်",
      "Virtual RAM (Virtual Memory) Tuning",
      "Local Group Policy Tweaks",
      "Windows Troubleshooting အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "STEP_BY_STEP", description: "Step-by-step tutorial (Myanmar)" },
      { type: "DEEP_EXPLAIN", description: "ပိုမို နက်နဲစွာ ရှင်းပြချက် (Deep Dive)" },
      { type: "TROUBLESHOOT", description: "Error ဖြစ်ရင် အကြောင်းအရင်းနှင့် ဖြေရှင်းနည်း" }
    ]
  },
  {
    id: 3,
    title: "Internet & Email",
    description: "Connecting to the digital world safely.",
    target: "အင်တာနက်နှင့် အီးမေးလ် အသုံးပြုလိုသူများအတွက်",
    category: "Intermediate",
    topics: [
      "Internet နှင့် World Wide Web (WWW)",
      "Browsers (Chrome, Edge, Firefox)",
      "Search Engine (Google) အသုံးပြုနည်း",
      "Advanced Google Search Techniques",
      "Internet Connection (Wi-Fi vs Ethernet)",
      "Modem နှင့် Router ကွာခြားချက်",
      "IP Address နှင့် DNS အခြေခံ",
      "URL နှင့် Website Structure",
      "Browser History, Cache နှင့် Cookies",
      "Bookmarks နှင့် Tabs စီမံခန့်ခွဲနည်း",
      "Incognito/Private Browsing",
      "Browser Extensions အသုံးပြုနည်း",
      "Email ဆိုတာဘာလဲ (Gmail အခြေခံ)",
      "Gmail Account အသစ်ဖွင့်နည်း",
      "Email ရေးသားနည်း (Compose)",
      "Attachments (File, Image) ပို့ဆောင်နည်း",
      "Email Inbox စီမံခြင်း (Labels, Folders)",
      "Spam နှင့် Junk Emails အကြောင်း",
      "Professional Email Etiquette",
      "Signature ဖန်တီးနည်း",
      "2-Step Verification (Account Security)",
      "Online Privacy နှင့် Safety Tips",
      "Social Media အခြေခံ (Facebook, LinkedIn)",
      "Cyber Bullying နှင့် Scam Awareness",
      "E-commerce နှင့် Online Shopping Safety",
      "Online Payments (KPay, Mobile Banking) Basics",
      "Video Conferencing (Zoom, Google Meet)",
      "Cloud Storage (Google Drive) အသုံးပြုနည်း",
      "Download နှင့် Upload သိကောင်းစရာများ",
      "FTP (File Transfer Protocol) အခြေခံ",
      "VPN (Virtual Private Network) အသုံးပြုခြင်း",
      "HTTP vs HTTPS (Security)",
      "Web Hosting နှင့် Domain အခြေခံ",
      "Internet of Things (IoT) ဆိုတာဘာလဲ",
      "Dark Web နှင့် Cyber Security Awareness",
      "Password Managers အသုံးပြုနည်း",
      "Public Wi-Fi အသုံးပြုရာတွင် သတိထားရန်",
      "Social Engineering နှင့် Phishing Attack",
      "Internet Speeds (Latency vs Bandwidth)",
      "Intranet vs Extranet",
      "Web Architecture အခြေခံ",
      "HTML/CSS ဆိုတာဘာလဲ (Introduction)",
      "IPv4 vs IPv6 ကွာခြားချက်",
      "DHCP နှင့် Static IP အကြောင်း",
      "Port Forwarding အခြေခံ",
      "Fiber Optic vs Broadband",
      "Satellite Internet အကြောင်း",
      "Web Cache နှင့် CDN အခြေခံ",
      "Cookies vs Session အကြောင်း",
      "Email Headers ဖတ်နည်း",
      "SMTP, IMAP, POP3 ကွာခြားချက်",
      "Email Filters နှင့် Rules တည်ဆောက်နည်း",
      "Mass Email နှင့် Newsletter Basics",
      "Web Browser Shortcut Keys",
      "Online Storage (Mega, Mediafire) Basics",
      "Sharing Files via Link (Permissions)",
      "Syncing Across Devices",
      "Internet Censorship အကြောင်း",
      "Digital Footprint စီမံခြင်း",
      "Ad-blockers အသုံးပြုခြင်း အကျိုး/အပြစ်",
      "Secure Shell (SSH) အခြေခံ",
      "Proxy Servers အကြောင်း",
      "Malvertising Awareness",
      "Internet Addiction နှင့် Wellbeing",
      "Internet Speed Test Tools",
      "Tethering နှင့် Hotspot အသုံးပြုနည်း",
      "Deep Web vs Dark Web",
      "BitTorrent အခြေခံ နားလည်မှု",
      "Open Source Intelligence (OSINT) Intro",
      "Internet အနှစ်ချုပ်နှင့် Future Trends"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Real-life Example Lesson" },
      { type: "DEEP_EXPLAIN", description: "နည်းပညာ အသေးစိတ် ရှင်းပြချက်" },
      { type: "TEMPLATE", description: "Email writing sample Auto Generate" }
    ]
  },
  {
    id: 4,
    title: "Microsoft Word",
    description: "Mastering professional document creation.",
    target: "စာစီစာရိုက်နှင့် ရုံးလုပ်ငန်း ကျွမ်းကျင်လိုသူများအတွက်",
    category: "Intermediate",
    topics: [
      "MS Word Interface နှင့် Ribbon Overview",
      "New Document တည်ဆောက်ခြင်းနှင့် Save လုပ်နည်း",
      "Font Formatting (Bold, Italic, Underline)",
      "Myanmar Unicode vs Win Font သုံးစွဲနည်း",
      "Paragraph Alignment နှင့် Indentation",
      "Line Spacing နှင့် Paragraph Spacing",
      "Bullets နှင့် Numbering အသုံးပြုနည်း",
      "Borders နှင့် Shading ထည့်သွင်းနည်း",
      "Copy, Cut, Paste နှင့် Format Painter",
      "Find နှင့် Replace လုပ်နည်း",
      "Page Setup (Margins, Orientation, Size)",
      "Header နှင့် Footer ထည့်သွင်းနည်း",
      "Page Numbering (Automatic)",
      "Tables တည်ဆောက်ခြင်းနှင့် Design ပြင်ဆင်ခြင်း",
      "Images နှင့် Shapes ထည့်သွင်းနည်း",
      "SmartArt နှင့် Charts အခြေခံ",
      "Hyperlinks နှင့် Bookmarks",
      "Symbols နှင့် Equation များ",
      "Columns (Newspaper Style) ခွဲနည်း",
      "Watermark နှင့် Page Color",
      "Table of Contents (Automatic) ပြုလုပ်နည်း",
      "Mail Merge အခြေခံ (Labels, Letters)",
      "Spelling နှင့် Grammar Check",
      "Track Changes နှင့် Comments",
      "Protecting Document with Password",
      "Exporting to PDF/XPS",
      "Templates အသုံးပြု၍ စာရွက်စာတမ်း ဖန်တီးနည်း",
      "Advanced Styles နှင့် Formatting",
      "Cross-references နှင့် Captions",
      "Footnotes နှင့် Endnotes",
      "Bibliography နှင့် Citations (APA Style)",
      "Macros in Word (Basics)",
      "Customizing the Quick Access Toolbar",
      "Restrict Editing နှင့် Permissions",
      "Comparing and Merging Documents",
      "Text Box နှင့် Drop Cap အသုံးပြုနည်း",
      "Envelopes နှင့် Labels Printing",
      "Quick Parts နှင့် AutoText",
      "Building Blocks Organizer",
      "Document Inspector (Metadata Remove)",
      "Accessibility Checker အသုံးပြုနည်း",
      "Navigation Pane (Headings Manage)",
      "Section Breaks (Next Page vs Continuous)",
      "Page Breaks vs Column Breaks",
      "Advanced Table Calculations",
      "Custom Margins and Gutter",
      "Thesaurus နှင့် Dictionary အသုံးပြုခြင်း",
      "Translating Text within Word",
      "Ink Annotations and Drawing",
      "Inserting Online Videos",
      "Sidebar and Pull Quote Design",
      "Creating Forms with Content Controls",
      "Developer Tab Overview",
      "XML Mapping Basics",
      "Object Linking and Embedding (OLE)",
      "Recovering Unsaved Documents",
      "PDF Reflow (Edit PDF in Word)",
      "Word Keyboard Shortcuts (Essential List)",
      "Control Key Shortcuts (Ctrl+A to Z)",
      "Function Key Shortcuts (F1 to F12)",
      "Formatting Shortcuts (Shift+Ctrl+F/P)",
      "Table Navigation Shortcuts",
      "Managing Large Documents (Master Docs)",
      "Standard CV Formatting Tips",
      "Office Letter Formatting Standard",
      "Win Font Keyboard Shortcuts in Word",
      "Unicode Typing Shortcuts in Word",
      "MS Word Mastery အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Letter / CV Template Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "ကျွမ်းကျင်နည်းလမ်းများ ရှင်းပြချက်" },
      { type: "QUIZ", description: "Exercise Question Auto Create" }
    ]
  },
  {
    id: 5,
    title: "Microsoft Excel",
        category: "Intermediate",
    description: "Data management and basic calculations.",
    target: "စာရင်းဇယားနှင့် တွက်ချက်မှု ကျွမ်းကျင်လိုသူများအတွက်",
    topics: [
      "Excel Interface (Cell, Row, Column)",
      "Workbooks နှင့် Worksheets အကြောင်း",
      "Data Entry နှင့် Data Types (Text, Number, Date)",
      "Cell Formatting (Font, Color, Border)",
      "Alignment နှင့် Merge Cells",
      "Number Formatting (Currency, Percentage)",
      "Basic Formulas (+, -, *, /)",
      "AutoSum (SUM, AVERAGE, COUNT, MAX, MIN)",
      "Relative vs Absolute Cell Reference ($)",
      "Fill Handle နှင့် Flash Fill အသုံးပြုနည်း",
      "Sorting Data (A-Z, Z-A)",
      "Filtering Data (Basic Filter)",
      "Conditional Formatting အခြေခံ",
      "Charts (Column, Pie, Line) တည်ဆောက်နည်း",
      "Freeze Panes နှင့် Split Window",
      "Page Layout နှင့် Printing Spreadsheet",
      "IF Function (Logical Test)",
      "VLOOKUP အခြေခံ နားလည်မှု",
      "HLOOKUP အခြေခံ",
      "Concatenate (Text Join) လုပ်နည်း",
      "Data Validation (Dropdown List)",
      "Pivot Tables (Data Analysis) Intro",
      "Named Ranges အသုံးပြုနည်း",
      "Error Types (#VALUE!, #REF!, #DIV/0!)",
      "Protecting Sheet နှင့် Workbook",
      "XLOOKUP (The Modern Lookup)",
      "INDEX and MATCH (Advanced Lookup)",
      "IFERROR and Logical Nesting",
      "Power Query အခြေခံ (Get & Transform)",
      "Advanced Pivot Charts",
      "Slicers နှင့် Timelines (Dashboards)",
      "What-If Analysis (Data Tables)",
      "Solver နှင့် Analysis ToolPak",
      "Array Formulas (Spill Functions)",
      "Excel VBA Macros (Recording)",
      "Excel Data Cleanup (Remove Duplicates)",
      "Text-to-Columns and Delimiters",
      "Importing Data from Web/API",
      "COUNTIF and SUMIF Functions",
      "AVERAGEIF and Multiple Criteria",
      "IFS and SWITCH Functions",
      "TEXTJOIN and CONCAT (Office 365)",
      "LEFT, RIGHT, MID (String Functions)",
      "FIND and SEARCH Functions",
      "DATE and TIME Calculations",
      "NETWORKDAYS and WORKDAY Functions",
      "VBA User Defined Functions (UDF)",
      "Protecting Cells while allowing Entry",
      "Data Modeling Basics",
      "Measure and Calculated Columns Intro",
      "Advanced Conditional Formatting (Formula based)",
      "Sparklines (Mini Charts)",
      "Group and Outline Data",
      "Subtotals (Automatic)",
      "Consolidating Multiple Sheets",
      "Excel Shortcuts (Navigation)",
      "Ctrl+Arrow Keys for Fast Movement",
      "Ctrl+Space and Shift+Space (Selection)",
      "Alt Key Shortcuts for Ribbon",
      "Ctrl+PageUp/Down (Sheet Switch)",
      "Paste Special (Values, Formulas, Transpose)",
      "Formula Auditing (Trace Precedents)",
      "Watch Window for Data Monitoring",
      "Custom Sort Levels",
      "Wildcards in Filter and Formulas (*, ?)",
      "Excel Data Dashboard Design",
      "Excel အနှစ်ချုပ်နှင့် Practice Tips"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Excel Practice Data Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Formula Explanation in Myanmar" }
    ]
  },
  {
    id: 6,
    title: "PowerPoint",
    description: "Creating effective presentations.",
    target: "တင်ပြမှုစွမ်းရည် တိုးတက်လိုသူများအတွက်",
    category: "Intermediate",
    topics: [
      "PowerPoint Interface နှင့် Slide Layouts",
      "New Slide ထည့်နည်းနှင့် Slide Master Intro",
      "Themes နှင့် Background Styles",
      "Text Box အသုံးပြုခြင်းနှင့် Formatting",
      "Images နှင့် Icons ထည့်သွင်းခြင်း",
      "Shapes နှင့် SmartArt Graphics",
      "Charts နှင့် Tables ထည့်သွင်းနည်း",
      "Transitions (Slide to Slide Effects)",
      "Animations (Object Effects) အခြေခံ",
      "Animation Pane အသုံးပြုနည်း",
      "Audio နှင့် Video ထည့်သွင်းခြင်း",
      "Hyperlinks နှင့် Action Buttons",
      "Slide Show Settings (From Beginning/Current)",
      "Presenter View အသုံးပြုနည်း",
      "Record Slide Show (Voice Over)",
      "Notes Page နှင့် Handouts",
      "Design Ideas (AI Tool) အသုံးပြုနည်း",
      "Grouping နှင့် Aligning Objects",
      "Crop နှင့် Image Adjustments",
      "Eyedropper Tool နှင့် Color Schemes",
      "Printing Slides နှင့် Notes",
      "Exporting to Video (MP4)",
      "Package for CD/Flash Drive",
      "Presentation Tips (The 10/20/30 Rule)",
      "Body Language နှင့် Presentation Skills",
      "Slide Master Advanced Layouts",
      "Custom Slide Shows ဖန်တီးနည်း",
      "Embedding Excel Data in PPT",
      "Interactive Quiz ဖန်တီးနည်း (PPT)",
      "Morph Transition (Advanced Effect)",
      "3D Models နှင့် SVG Icons အသုံးပြုခြင်း",
      "Zoom Feature (Slide/Section Zoom)",
      "Ink Tools နှင့် Laser Pointer",
      "Collaborating on OneDrive",
      "Converting PPT to PDF/Images",
      "Animation Triggers (Click to show)",
      "Motion Paths (Advanced Animation)",
      "Emphasis Effects အသုံးပြုနည်း",
      "Combining Shapes (Merge Shapes)",
      "Compressing Media Files",
      "SmartArt to Shapes Conversion",
      "Slide Background Removal",
      "Photo Album Feature",
      "Using Rehearse with Coach (AI)",
      "Live Captions and Subtitles",
      "Screen Recording within PPT",
      "Hiding Slides for Different Audiences",
      "Setting up Self-Running Kiosk",
      "Using Ink to Text/Shape",
      "PowerPoint Keyboard Shortcuts",
      "F5 and Shift+F5 (Start Show)",
      "B and W keys during Slide Show",
      "Ctrl+P for Pen during Show",
      "Ctrl+M for New Slide",
      "Managing Linked Files",
      "Standard Slide Sizes (4:3 vs 16:9)",
      "Exporting Slides as High Res Images",
      "Creating Infographics in PPT",
      "Digital Signage with PowerPoint",
      "Using Add-ins for PPT",
      "Accessibility Standards for Slides",
      "Professional Branding in PPT",
      "Handling Q&A Sessions",
      "PowerPoint အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Slide Content Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Professional Skills Deep Dive" },
      { type: "STEP_BY_STEP", description: "Presentation Script Auto Generate" }
    ]
  },
  {
    id: 7,
    title: "AI for Daily Life",
        category: "Ai",

    description: "Leveraging modern AI tools for productivity.",
    target: "AI ကို ထိရောက်စွာ အသုံးပြုလိုသူများအတွက်",
    topics: [
      "Artificial Intelligence (AI) ဆိုတာဘာလဲ",
      "Generative AI အကြောင်း နားလည်မှု",
      "Gemini နှင့် ChatGPT နှိုင်းယှဉ်ချက်",
      "Prompt Engineering (အခြေခံ)",
      "ထိရောက်သော Prompt ရေးသားနည်းများ",
      "AI ဖြင့် Email ရေးသားနည်း",
      "AI ကို အသုံးပြု၍ ဘာသာပြန်ဆိုခြင်း",
      "AI ဖြင့် ခရီးစဉ် (Itinerary) ရေးဆွဲခြင်း",
      "AI နှင့် သင်ယူမှု (Self-Study Helper)",
      "AI ဖြင့် Content Writing လုပ်ခြင်း",
      "AI Image Generation (DALL-E, Adobe Firefly)",
      "AI ဖြင့် Resume နှင့် CV ပြုပြင်ခြင်း",
      "AI ကို Coding အခြေခံတွင် အသုံးပြုနည်း",
      "Google Lens (AI Vision) အသုံးပြုနည်း",
      "AI Voice Assistants (Siri, Google Assistant)",
      "AI in Microsoft Office (Copilot Intro)",
      "AI for Video Editing (Descript, Runway)",
      "AI Ethics နှင့် တာဝန်ယူမှုရှိစွာ သုံးစွဲရေး",
      "Fake News နှင့် Deepfakes ခွဲခြားနည်း",
      "AI for Math and Science Problems",
      "AI နှင့် Data Privacy သိကောင်းစရာ",
      "Personal AI Tutor အဖြစ် အသုံးပြုနည်း",
      "AI ဖြင့် သတင်းအနှစ်ချုပ် (Summarization)",
      "AI in Social Media (Algorithm Basics)",
      "Claude နှင့် Perplexity AI အခြေခံ",
      "AI Agent ဆိုတာဘာလဲ (Intro)",
      "Custom GPTs တည်ဆောက်နည်း",
      "AI ဖြင့် Music Generation (Suno/Udio)",
      "AI Browser Extensions (Monica/Harpa)",
      "Automation with Zapier and AI",
      "Midjourney for Professional Art",
      "AI for Language Learning (Duolingo/AI)",
      "AI Video Avatars (HeyGen/Synthesia)",
      "AI Logo Generation",
      "Prompting for Specific Roles (Law, Med, Teach)",
      "AI Text-to-Speech (ElevenLabs)",
      "AI Meeting Assistants (Otter.ai)",
      "AI for Spreadsheet Analysis",
      "Negative Prompts in Image AI",
      "In-painting and Out-painting Basics",
      "AI for Financial Planning",
      "AI and Job Market (New Opportunities)",
      "Detecting AI Content (AI Detectors)",
      "Bias in AI Algorithms",
      "Prompt Chaining Techniques",
      "Few-shot vs Zero-shot Prompting",
      "Context Windows in LLMs",
      "Vector Databases (High Level Intro)",
      "AI Hallucinations အကြောင်း",
      "AI for Legal Research Intro",
      "AI and Mental Health Apps",
      "AI for Genealogy and History",
      "AI in E-commerce (Recommendations)",
      "Open Source LLMs (Llama, Mistral)",
      "Building a Local AI Server (Basic)",
      "AI for Travel Planning Pro",
      "AI for Scientific Research",
      "The Future of Work with AI",
      "Prompts for Different Professions",
      "AI နှင့် လူသားတို့၏ ပူးပေါင်းဆောင်ရွက်မှု",
      "AI for Daily Life အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Prompt Example Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "AI Internal Working Detail" },
      { type: "EXPLAIN", description: "Beginner-friendly Explanation" }
    ]
  },
  {
    id: 8,
    title: "Myanmar Typing",
    description: "Fast and accurate Myanmar language typing.",
    target: "မြန်မာစာရိုက် ကျွမ်းကျင်လိုသူများအတွက်",
    category: "Specialized",
    topics: [
      "Myanmar Unicode Standard အကြောင်း",
      "Zawgyi နှင့် Unicode ကွာခြားချက်",
      "Pyidaungsu Keyboard Layout နားလည်မှု",
      "လက်ကွက် အခြေခံ (Finger Placement)",
      "Home Row Keys Practice",
      "Top Row Keys Practice",
      "Bottom Row Keys Practice",
      "Shift Key နှင့် အဆင့်မြင့် ဗျည်းများ",
      "သရနှင့် ဗျည်းတွဲ ရိုက်နည်းများ",
      "ဆင့်ဆင့် (Stacked Characters) ရိုက်နည်း",
      "Numbers နှင့် Symbols ရိုက်နည်း",
      "Typing Speed Test (Unicode)",
      "Win Font အသုံးပြုပုံ (Legacy System)",
      "Font Converters အသုံးပြုနည်း",
      "Myanmar Typing Shortcuts",
      "Win Font Keyboard Layout (Aung/WinInnwa)",
      "Win Font Character Mapping (Key by Key)",
      "Win Font vs Unicode Hand Placement",
      "Common Win Font Symbols (Key combinations)",
      "Win Font to Unicode Conversion Shortcuts",
      "Typing common Myanmar Honorifics",
      "Shortcuts for Myanmar Names (Quick strings)",
      "Win Font Table Formatting Layout",
      "Unicode Language Settings in Windows 11",
      "Gboard Myanmar Layout (Mobile)",
      "Keyman Keyboard Configuration",
      "Myanmar Language Pack for Office",
      "Typing complex Pali strings (Shortcuts)",
      "AltGr + Key combinations for Unicode",
      "Myanmar Zero (၀) vs English Zero (0)",
      "Myanmar Letter U (ဥ) vs Letter O (ဝ)",
      "Myanmar Letter Wa (ဝ) vs Zero (၀)",
      "Smart Quotes in Myanmar Typing",
      "Keyboard Heatmap for Myanmar Typing",
      "Accuracy vs Speed Training Drills",
      "Blind Typing Myanmar Practice",
      "Win Font Layout: Top Row Shifted",
      "Win Font Layout: Bottom Row Keys",
      "Win Font Layout: Consonant Stackers",
      "Win Font Layout: Medials (Ya-pin, etc.)",
      "Shortcuts for common Myanmar Suffixes",
      "Office standard Myanmar font sizes",
      "Myanmar Font Rendering Issues Fix",
      "Legacy document repair (Win Font)",
      "OCR for Myanmar Win Font Docs",
      "Myanmar Digital Content Standards",
      "Typography in Myanmar Design",
      "Typing Speed Competitions (Intro)",
      "Keyboard Ergonomics for Fast Typing",
      "Standardizing Myanmar Documents",
      "Advanced Key Combinations (AltGr)",
      "Win Font Typing Accuracy Drills",
      "Win Font vs Unicode Side-by-Side",
      "Myanmar Typing အနှစ်ချုပ်"
    ],
    aiFeatures: [
      { type: "PRACTICE_DATA", description: "Typing Practice Text Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "Keyboard Layout Details" },
      { type: "TROUBLESHOOT", description: "Error correction suggestion" }
    ]
  },
  {
    id: 9,
    title: "Computer Error & Fixing",
        category: "Computer Error",

    description: "Basic troubleshooting and hardware maintenance.",
    target: "ကွန်ပျူတာ ပြဿနာများကို ကိုယ်တိုင်ဖြေရှင်းလိုသူများအတွက်",
    topics: [
      "Troubleshooting Methodology (အခြေခံ)",
      "Computer မတက်ခြင်း (No Power) ဖြေရှင်းနည်း",
      "Blue Screen of Death (BSOD) အကြောင်း",
      "Windows Slow ဖြစ်ခြင်းကို ဖြေရှင်းနည်း",
      "Internet Connection ပြဿနာများ",
      "Wi-Fi မချိတ်ဆက်နိုင်ခြင်း",
      "USB Drive မပေါ်ခြင်း (Not Recognized)",
      "Keyboard နှင့် Mouse အလုပ်မလုပ်ခြင်း",
      "Audio/Sound ပြဿနာများ",
      "Printer မထွက်ခြင်း (Offline/Error)",
      "Software Hang/Freeze ဖြစ်ခြင်း",
      "Computer Overheating ပြဿနာ",
      "Virus/Malware ကူးစက်ခံရခြင်း လက္ခဏာများ",
      "Malware ဖယ်ရှားနည်း (Manual vs Auto)",
      "System Recovery Options",
      "Safe Mode သို့ ဝင်ရောက်နည်း",
      "Driver Update လုပ်နည်း",
      "Task Manager ဖြင့် Performance စစ်ဆေးနည်း",
      "Disk Cleanup နှင့် Defragmentation",
      "RAM စစ်ဆေးခြင်းနှင့် သန့်ရှင်းရေး",
      "Hard Disk Health (S.M.A.R.T) စစ်ဆေးနည်း",
      "Battery Life နှင့် Maintenance",
      "Windows Activation Errors",
      "Application Error Codes ဖြေရှင်းနည်း",
      "Creating Bootable USB",
      "Windows ပြန်တင်နည်း (Clean Install Intro)",
      "Data Recovery (Deleted Files)",
      "Remote Desktop/TeamViewer အခြေခံ",
      "BIOS/UEFI Settings အခြေခံ",
      "CMOS Battery Replacement",
      "Network Troubleshooting (ping, tracert)",
      "Fixing Corrupt System Files (SFC)",
      "Partition Loss Recovery",
      "Diagnosing Motherboard Beep Codes",
      "Router Reset and Configuration",
      "Hardware Component Replacement",
      "Cloud Backup for Recovery",
      "Event Viewer Error Log Reading",
      "Check Disk (chkdsk) Utility",
      "Memory Diagnostic Tool (mdsched)",
      "Safe Mode vs Clean Boot",
      "Advanced Startup Options",
      "Power Supply Testing (Basic)",
      "GPU Artifacts and Fixing",
      "Thermal Paste Replacement Guide",
      "Cleaning Sticky Keyboards",
      "Fixing Flickering Monitors",
      "Data Recovery with Recuva/PhotoRec",
      "Windows Registry Repair",
      "Malwarebytes and Defender Scan pro",
      "Ransomware Protection Basics",
      "Fixing Audio Jack Problems",
      "Webcam not working fix",
      "Bluetooth Pairing Issues",
      "Updating BIOS Safely",
      "Resolving Driver Conflicts",
      "Uninstalling Stubborn Apps",
      "Fixing Windows Store Errors",
      "Restoring System Image",
      "Hardware Upgrade Paths (RAM/SSD)",
      "Diagnosing PSU Failure",
      "Troubleshooting Port Failures",
      "Cable Replacement vs Repair",
      "Hardware Maintenance Checklist"
    ],
    aiFeatures: [
      { type: "TROUBLESHOOT", description: "Error Input → Solution Auto Show" },
      { type: "DEEP_EXPLAIN", description: "Technical Fix Explained" },
      { type: "STEP_BY_STEP", description: "Beginner-friendly Fix Steps" }
    ]
  },
  {
    id: 10,
    title: "Windows OS Mastery",
    description: "Complete mastery of Windows operating system.",
    target: "Windows အထူးကျွမ်းကျင်လိုသူများအတွက်",
    category: "Advanced",
    topics: [
      "Windows 11 Advanced Features",
      "PowerShell Scripting Mastery",
      "Windows Server Basics",
      "Active Directory Fundamentals",
      "Group Policy Advanced Management",
      "Windows Registry Deep Dive",
      "Windows Security Hardening",
      "Windows Performance Tuning",
      "Windows Troubleshooting Advanced",
      "Windows Deployment Tools",
      "Windows Update Management",
      "Windows Networking Advanced",
      "Windows Storage Spaces",
      "Windows Virtualization (Hyper-V)",
      "Windows Containers and WSL2",
      "Windows Remote Management",
      "Windows Event Logging Analysis",
      "Windows Backup and Recovery Pro",
      "Windows Firewall Configuration",
      "Windows Defender Advanced Settings",
      "BitLocker Drive Encryption",
      "Windows Hello for Business",
      "Windows Credential Manager",
      "Windows Task Scheduler Advanced",
      "Windows Services Management",
      "Windows Disk Management Pro",
      "Windows File System (NTFS, ReFS)",
      "Windows User Account Control (UAC)",
      "Windows App Compatibility",
      "Windows System Restore Advanced",
      "Windows Memory Management",
      "Windows Process Management",
      "Windows Thread Management",
      "Windows Kernel Architecture",
      "Windows Boot Process Deep Dive",
      "Windows Shutdown and Hibernate",
      "Windows Sleep States",
      "Windows Power Management",
      "Windows Device Drivers Deep",
      "Windows Hardware Abstraction Layer",
      "Windows API Programming Basics",
      "Windows COM and DCOM",
      "Windows WMI (Windows Management Instrumentation)",
      "Windows Event Tracing (ETW)",
      "Windows Performance Counters",
      "Windows Resource Monitor Advanced",
      "Windows Reliability Monitor",
      "Windows System Information Tool",
      "Windows Command Line Tools Advanced",
      "Windows Batch Scripting",
      "Windows VBScript Basics",
      "Windows JScript Basics",
      "Windows .NET Framework Integration",
      "Windows Runtime (WinRT)",
      "Windows Universal Windows Platform (UWP)",
      "Windows Store Apps Management",
      "Windows Sandbox Advanced",
      "Windows Subsystem for Android",
      "Windows Game Mode and Optimization",
      "Windows OS Mastery Summary"
    ],
    aiFeatures: [
      { type: "STEP_BY_STEP", description: "Advanced Windows Configuration Steps" },
      { type: "DEEP_EXPLAIN", description: "Windows Internal Architecture Details" },
      { type: "TROUBLESHOOT", description: "Complex Windows Error Resolution" }
    ]
  },
  {
    id: 11,
    title: "Digital Skills for Work & Business",
    description: "အလုပ်လုပ်ရာမှာ တကယ်အသုံးချရမယ့် Digital Skill များ",
    target: "အလုပ်လုပ်ငန်းများတွင် ဒစ်ဂျစ်တယ် ကျွမ်းကျင်လိုသူများအတွက်",
    category: "Intermediate",
    topics: [
      "Google Drive (Docs, Sheets, Slides)",
      "Cloud Storage Concept",
      "Online Form (Google Form)",
      "Basic Online Collaboration",
      "File Sharing & Permission Control",
      "Microsoft Teams အခြေခံ",
      "Zoom Meeting စီမံခန့်ခွဲခြင်း",
      "Video Conferencing Etiquette",
      "Online Meeting Recording",
      "Screen Sharing နည်းလမ်းများ",
      "Virtual Backgrounds အသုံးပြုခြင်း",
      "Meeting Invitations ပို့ဆောင်ခြင်း",
      "Calendar Scheduling (Outlook/Google)",
      "Time Zone Management",
      "Meeting Minutes ရေးသားခြင်း",
      "Project Management Tools (Trello, Asana)",
      "Task Assignment နှင့် Tracking",
      "Deadline Setting နည်းလမ်းများ",
      "Workflow Automation (Zapier)",
      "Email Templates တည်ဆောက်ခြင်း",
      "Professional Email Signatures",
      "Email Filters နှင့် Rules",
      "Spam Management",
      "Email Encryption Basics",
      "Digital Signatures",
      "Document Version Control",
      "File Naming Conventions",
      "Cloud Backup Strategies",
      "Data Synchronization",
      "Offline Access စီမံခန့်ခွဲခြင်း",
      "Google Workspace vs Microsoft 365",
      "Collaborative Document Editing",
      "Commenting and Suggestions",
      "Track Changes in Documents",
      "Review and Approval Processes",
      "Digital Contracts အခြေခံ",
      "E-signature Tools (DocuSign)",
      "Legal Document Templates",
      "Invoice Creation နည်းလမ်းများ",
      "Expense Tracking Apps",
      "Budget Planning Tools",
      "Financial Reporting Basics",
      "CRM Software Introduction",
      "Customer Data Management",
      "Lead Generation Online",
      "Social Media Marketing Basics",
      "Content Calendar Planning",
      "Brand Guidelines Digital",
      "Logo Design Tools",
      "Business Card Templates",
      "Presentation Design Principles",
      "Data Visualization (Charts/Graphs)",
      "Infographic Creation",
      "Video Editing Basics",
      "Podcast Production Intro",
      "Live Streaming Setup",
      "Webinar Hosting",
      "E-commerce Platforms",
      "Online Store Setup",
      "Payment Gateway Integration",
      "Inventory Management Digital",
      "Customer Service Chatbots",
      "Help Desk Software",
      "Ticketing Systems",
      "Knowledge Base Creation",
      "Remote Work Tools",
      "VPN for Business",
      "Cybersecurity Awareness",
      "Password Management Enterprise",
      "Two-Factor Authentication",
      "Data Privacy Regulations (GDPR)",
      "Compliance Training Basics",
      "Digital Accessibility Standards",
      "Website Building Tools",
      "SEO Fundamentals",
      "Analytics Tracking",
      "Social Media Analytics",
      "Email Marketing Campaigns",
      "Newsletter Design",
      "A/B Testing for Marketing",
      "Lead Magnets Creation",
      "Sales Funnel Design",
      "Customer Journey Mapping",
      "Business Intelligence Tools",
      "Data Analysis for Business",
      "Dashboard Creation",
      "Reporting Automation",
      "Cloud Computing for Business",
      "SaaS vs PaaS vs IaaS",
      "Cost Optimization Cloud",
      "Digital Transformation Strategy",
      "Innovation in Digital Business",
      "Future of Work Trends",
      "Digital Skills for Work & Business Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 12,
    title: "AI + Automation (Advanced)",
    description: "AI ကို အလုပ်တွေနဲ့ ချိတ်ဆက်အသုံးချခြင်း",
    target: "AI နှင့် Automation ကို အလုပ်တွင် အသုံးချလိုသူများအတွက်",
    category: "Advanced",
    topics: [
      "AI for Office Automation",
      "Prompt Engineering Advanced",
      "AI + Excel / Docs",
      "No-Code Tools",
      "AI Ethics & Safety",
      "AI Workflow Integration",
      "Automated Report Generation",
      "Intelligent Document Processing",
      "AI-Powered Data Analysis",
      "Machine Learning for Business",
      "Natural Language Processing Applications",
      "Computer Vision in Business",
      "Robotic Process Automation (RPA)",
      "Chatbot Development for Business",
      "AI Customer Service Solutions",
      "Predictive Analytics Implementation",
      "AI-Driven Decision Making",
      "Automated Marketing Campaigns",
      "Personalized Content Generation",
      "AI Content Moderation",
      "Voice AI Assistants",
      "AI Translation Services",
      "Automated Scheduling Systems",
      "Smart Calendar Management",
      "AI Meeting Summarization",
      "Automated Email Processing",
      "Intelligent Spam Filtering",
      "AI Document Classification",
      "Automated Invoice Processing",
      "AI Contract Analysis",
      "Legal Document AI Review",
      "AI Financial Forecasting",
      "Automated Budget Tracking",
      "AI Fraud Detection",
      "Risk Assessment Automation",
      "AI Supply Chain Optimization",
      "Inventory Prediction Models",
      "AI Quality Control",
      "Automated Testing Frameworks",
      "AI Code Generation",
      "Low-Code Development Platforms",
      "API Integration Automation",
      "Workflow Orchestration",
      "Event-Driven Automation",
      "AI Monitoring and Alerting",
      "Performance Analytics Automation",
      "AI Anomaly Detection",
      "Automated Backup Systems",
      "AI Security Monitoring",
      "Threat Intelligence Automation",
      "AI Compliance Monitoring",
      "Automated Audit Trails",
      "AI Training Data Management",
      "Model Deployment Automation",
      "AI Model Monitoring",
      "Version Control for AI Models",
      "AI Bias Detection and Mitigation",
      "Ethical AI Implementation",
      "AI Transparency Frameworks",
      "Responsible AI Governance",
      "AI Safety Protocols",
      "Human-AI Collaboration Models",
      "AI Skill Development",
      "Automation Career Paths",
      "Future of AI in Business",
      "AI + Automation Summary"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "Prompt Example Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "AI Internal Working Detail" },
      { type: "EXPLAIN", description: "Beginner-friendly Explanation" }
    ]
  },
  {
    id: 13,
    title: "Social Media & Online Safety",
        category: "Social Media",

    description: "Social Media ကို ထိရောက်ပြီး လုံခြုံစွာ အသုံးချနိုင်ဖို့",
    target: "Social Media နှင့် Online Safety ကို လေ့လာလိုသူများအတွက်",
    topics: [
      "Facebook Page / Profile Professional Setup",
      "Content Posting Strategy",
      "Basic Graphic Tools (Canva)",
      "Online Scam & Phishing Protection",
      "Privacy & Account Security",
      "Social Media Platform Overview",
      "LinkedIn Professional Networking",
      "Twitter/X for Business Communication",
      "Instagram Business Account Setup",
      "TikTok Content Creation",
      "YouTube Channel Management",
      "Social Media Content Calendar",
      "Hashtag Strategy and Research",
      "Social Media Analytics Basics",
      "Engagement Best Practices",
      "Community Management",
      "Social Media Advertising",
      "Facebook Ads Manager",
      "Instagram Shopping Features",
      "Influencer Marketing Basics",
      "Brand Voice and Tone",
      "Content Creation Tools",
      "Photo Editing with Mobile Apps",
      "Video Editing for Social Media",
      "Live Streaming on Social Platforms",
      "Storytelling Techniques",
      "Social Media Crisis Management",
      "Reputation Management Online",
      "Digital Footprint Awareness",
      "Password Security Best Practices",
      "Two-Factor Authentication Setup",
      "Privacy Settings on Social Media",
      "Data Privacy Laws (GDPR, CCPA)",
      "Cyberbullying Prevention",
      "Online Harassment Recognition",
      "Safe Online Shopping",
      "Digital Payment Security",
      "VPN Usage for Online Safety",
      "Antivirus and Security Software",
      "Malware Protection",
      "Phishing Email Detection",
      "Social Engineering Awareness",
      "Fake News Identification",
      "Online Identity Protection",
      "Parental Controls Setup",
      "Child Online Safety",
      "Digital Citizenship Education",
      "Ethical Social Media Use",
      "Copyright and Fair Use",
      "Image Rights and Permissions",
      "Social Media Legal Compliance",
      "Platform-Specific Policies",
      "Content Moderation Guidelines",
      "Algorithm Understanding",
      "SEO for Social Media",
      "Cross-Platform Content Strategy",
      "Social Media ROI Measurement",
      "Influencer Collaboration Ethics",
      "Brand Partnership Guidelines",
      "Social Media Automation Tools",
      "Scheduling Posts Effectively",
      "A/B Testing for Content",
      "Social Listening Tools",
      "Competitor Analysis Online",
      "Trend Spotting and Adaptation",
      "Social Media for Customer Service",
      "Chatbot Integration",
      "Social Commerce Setup",
      "E-commerce on Social Platforms",
      "User-Generated Content Management",
      "Social Media Metrics Deep Dive",
      "Conversion Tracking",
      "Social Media & Online Safety Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 14,
    title: "Daily Life Use Case Learning",
    description: "နေ့စဉ်ဘဝနဲ့ ချိတ်ပြီး သင်ခြင်း",
    target: "နေ့စဉ်ဘဝတွင် တကယ်ဖြစ်နိုင်သော နည်းပညာပြဿနာများကို ဖြေရှင်းနည်းလမ်းများကို လေ့လာလိုသူများအတွက်",
    category: "Beginner",
    topics: [
      "USB ပျောက်သွားရင် ဘာလုပ်မလဲ",
      "Email မဝင်ရင် ဘယ်လိုဖြေရှင်းမလဲ",
      "Facebook Account Hack မဖြစ်အောင်",
      "ဖုန်းလုသွားရင် ဘာလုပ်မလဲ",
      "Internet နှေးတာ ပြင်နည်း",
      "Wi-Fi Password မေ့သွားရင်",
      "File ပျက်သွားရင် ပြန်ရနည်း",
      "Printer အလုပ်မလုပ်ရင်",
      "Computer ရပ်သွားရင် Data ကယ်နည်း",
      "Phone လောင်သွားရင် ဘာလုပ်မလဲ",
      "Screen Lock မေ့သွားရင်",
      "App တွေ Crash ဖြစ်ရင်",
      "Update လုပ်ပြီး ပြဿနာဖြစ်ရင်",
      "Battery မြန်ဆင်းရင်",
      "Storage ပြည့်သွားရင်",
      "Bluetooth မချိတ်ဆက်နိုင်ရင်",
      "Speaker အသံမထွက်ရင်",
      "Keyboard အလုပ်မလုပ်ရင်",
      "Mouse အလုပ်မလုပ်ရင်",
      "Monitor မီးမထွက်ရင်",
      "USB Port အလုပ်မလုပ်ရင်",
      "Webcam အလုပ်မလုပ်ရင်",
      "Microphone အလုပ်မလုပ်ရင်",
      "Touchpad အလုပ်မလုပ်ရင်",
      "VPN မချိတ်ဆက်နိုင်ရင်",
      "Online စာတင်ရင် ဘာလိုအရင်လုပ်မလဲ",
      "Job Application Online ဖြည့်နည်း",
      "Zoom မှာ Class တက်နည်း",
      "Google Meet မှာ Meeting လုပ်နည်း",
      "Online Shopping လုပ်နည်း",
      "Online Banking အသုံးပြုနည်း",
      "Mobile Banking App သုံးနည်း",
      "Digital Payment လုပ်နည်း",
      "Credit Card နဲ့ Online ပို့နည်း",
      "E-wallet အသုံးပြုနည်း",
      "QR Code ဖတ်နည်း",
      "Google Drive မှာ File တင်နည်း",
      "Cloud Storage ကနေ Download လုပ်နည်း",
      "Google Docs မှာ စာရိုက်နည်း",
      "Google Sheets မှာ စာရင်းသွင်းနည်း",
      "Google Slides နဲ့ Presentation လုပ်နည်း",
      "Canva နဲ့ Design လုပ်နည်း",
      "YouTube မှာ Video ကြည့်နည်း",
      "Facebook မှာ Post တင်နည်း",
      "Messenger မှာ Message ပို့နည်း",
      "Viber အသုံးပြုနည်း",
      "Telegram အသုံးပြုနည်း",
      "Line App အသုံးပြုနည်း",
      "TikTok မှာ Video တင်နည်း",
      "Instagram အသုံးပြုနည်း",
      "Twitter/X အသုံးပြုနည်း",
      "LinkedIn Profile တည်ဆောက်နည်း",
      "Password Manager သုံးနည်း",
      "2FA Setup လုပ်နည်း",
      "Email Spam ကို စစ်ထုတ်နည်း",
      "Pop-up Ad တားနည်း",
      "Phone မှာ App ထည့်နည်း",
      "App Permissions စစ်ဆေးနည်း",
      "Daily Life Use Case Learning Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "QUIZ", description: "Simple Quiz (MCQ) Auto Generate" }
    ]
  },
  {
    id: 15,
    title: "Basic IT Support Awareness",
        category: "It Support",

    description: "IT မဟုတ်ပေမယ့် IT နားလည်စေဖို့",
    target: "IT အခြေခံကို နားလည်စေလိုသူများအတွက်",
    topics: [
      "Common Office IT Problems",
      "Software Install / Uninstall",
      "Driver Concept (Printer, USB)",
      "Virus & Antivirus (Beginner)",
      "When to Call IT Technician",
      "Printer Not Responding Issues",
      "Computer Slow Performance",
      "Internet Connection Problems",
      "Email Not Working",
      "Password Reset Procedures",
      "Account Lockout Resolution",
      "Screen Display Issues",
      "Audio Not Working",
      "USB Device Not Recognized",
      "Keyboard/Mouse Problems",
      "Software Crashing",
      "Application Not Opening",
      "Windows Update Issues",
      "Blue Screen Errors",
      "Battery and Power Issues",
      "Overheating Problems",
      "Data Backup Basics",
      "File Recovery Methods",
      "Network Cable Issues",
      "Wi-Fi Connection Drops",
      "VPN Connection Problems",
      "Remote Access Setup",
      "Firewall Settings Basics",
      "Antivirus Scan Procedures",
      "Malware Removal Steps",
      "Phishing Email Identification",
      "Suspicious Link Detection",
      "Safe Browsing Practices",
      "Password Management",
      "Two-Factor Authentication",
      "Data Privacy Basics",
      "Confidential Information Handling",
      "Physical Security Awareness",
      "Cable Management Basics",
      "Hardware Inventory Basics",
      "Software License Compliance",
      "Operating System Basics",
      "File Explorer Navigation",
      "Folder Organization",
      "Cloud Storage Usage",
      "Document Version Control",
      "Printing Troubleshooting",
      "Scanning Documents",
      "Video Conferencing Basics",
      "Presentation Equipment",
      "Mobile Device Management",
      "BYOD Policy Basics",
      "Ticketing System Usage",
      "IT Support Request Process",
      "Escalation Procedures",
      "Documentation Requirements",
      "Change Management Basics",
      "Incident Reporting",
      "Service Request Fulfillment",
      "Basic Hardware Maintenance",
      "Cleaning and Care Guidelines",
      "Basic IT Support Awareness Summary"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Lesson explanation ကို မြန်မာလို Auto Generate" },
      { type: "DEEP_EXPLAIN", description: "အသေးစိတ် ထပ်မံရှင်းပြချက် (Detailed Explain)" },
      { type: "TROUBLESHOOT", description: "Simple Troubleshooting Guide Auto Generate" }
    ]
  },
  {
    id: 16,
    title: "IT Career & Freelancing",
    description: "သင်ထားတဲ့ Skill ကို ငွေဖြစ်အောင် ပြောင်းခြင်း",
    target: "IT Career နှင့် Freelancing ကို စလိုလိုသူများအတွက်",
    category: "Advanced",
    topics: [
      "IT Career Paths Overview",
      "Freelancing Platforms",
      "Portfolio Building",
      "CV for IT Jobs",
      "Interview Preparation",
      "Resume Writing Tips",
      "LinkedIn Profile Optimization",
      "GitHub Profile Setup",
      "Personal Website Creation",
      "Online Presence Management",
      "Professional Networking",
      "Industry Certifications",
      "Skill Assessment and Gap Analysis",
      "Setting Career Goals",
      "Job Search Strategies",
      "Company Research",
      "Salary Negotiation",
      "Work-Life Balance",
      "Remote Work Setup",
      "Time Management",
      "Productivity Tools",
      "Communication Skills",
      "Team Collaboration",
      "Project Management Basics",
      "Agile Methodology Intro",
      "Scrum Basics",
      "Business Communication",
      "Client Management",
      "Contract Writing",
      "Invoicing Basics",
      "Tax Planning for Freelancers",
      "Financial Literacy",
      "Pricing Strategies",
      "Pitching Services",
      "Proposal Writing",
      "Client Acquisition",
      "Retainer Agreements",
      "Building Long-term Clients",
      "Testimonials and References",
      "Personal Branding",
      "Marketing Yourself",
      "Social Media for Business",
      "Content Marketing",
      "Email Outreach",
      "Cold Calling Basics",
      "Networking Events",
      "Conferences and Meetups",
      "Online Courses Creation",
      "Passive Income Streams",
      "Side Projects",
      "App Development",
      "Web Development",
      "Data Analysis Services",
      "Consulting Services",
      "Technical Writing",
      "Translation Services",
      "Graphic Design Services",
      "Video Editing Services",
      "Virtual Assistant Services",
      "Customer Support Services",
      "IT Career & Freelancing Summary"
    ],
    aiFeatures: [
      { type: "TEMPLATE", description: "CV/Resume Template Auto Generate" },
      { type: "EXPLAIN", description: "Career Advice in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Freelancing Strategies Deep Dive" }
    ]
  },
  {
    id: 17,
    title: "HTML - Web Development Foundation",
    description: "Building modern websites starting with HTML fundamentals.",
    target: "Web Development ကို စလေတော့မယ့် သူများအတွက်",
    category: "Web Development",
    topics: [
      "HTML ဆိုတာဘာလဲ (Introduction)",
      "HTML Document Structure (Doctype, html, head, body)",
      "Text Editors ရွေးချယ်နည်း (VS Code, Sublime)",
      "Basic Tags (html, head, title, body)",
      "Headings (h1 to h6)",
      "Paragraphs (p tag)",
      "Line Breaks (br tag)",
      "Horizontal Rules (hr tag)",
      "Comments ထည့်သွင်းနည်း",
      "Text Formatting (b, i, u, strong, em)",
      "Superscript နှင့် Subscript (sup, sub)",
      "Lists တည်ဆောက်ခြင်း (ul, ol, li)",
      "Definition Lists (dl, dt, dd)",
      "Links (a tag) ထည့်သွင်းနည်း",
      "Absolute vs Relative URLs",
      "Link to Same Page (Anchor Links)",
      "Images (img tag) ထည့်သွင်းခြင်း",
      "Image Attributes (src, alt, width, height)",
      "Image Formats (JPG, PNG, GIF, WebP)",
      "Tables (table, tr, td, th)",
      "Table Headers နှင့် Captions",
      "Rowspan နှင့် Colspan",
      "Forms (form tag) အခြေခံ",
      "Input Types (text, password, email, number)",
      "Textarea နှင့် Select Dropdown",
      "Checkboxes နှင့် Radio Buttons",
      "Submit နှင့် Reset Buttons",
      "Form Validation (required, pattern)",
      "HTML5 Semantic Elements (header, nav, main, footer)",
      "Article နှင့် Section Elements",
      "Aside, Figure နှင့် Figcaption",
      "Inline vs Block Elements",
      "Div နှင့် Span ကွာခြားချက်",
      "Character Entities (&nbsp;, <, >, &amp;)",
      "Meta Tags အရေးပါပုံ",
      "Favicon ထည့်သွင်းခြင်း",
      "HTML Entities အသုံးပြုခြင်း",
      "Iframes (embed external content)",
      "Audio နှင့် Video Tags",
      "Progress Bar နှင့် Meter Elements",
      "Data Attributes အသုံးပြုခြင်း",
      "HTML5 New Input Types (date, color, range)",
      "Content Editable Attribute",
      "Drag and Drop API Intro",
      "Canvas Element အခြေခံ",
      "SVG Graphics in HTML",
      "Accessibility (alt, aria-label, semantic HTML)",
      "SEO Basics with HTML",
      "Responsive Images (srcset, picture)",
      "Lazy Loading Images",
      "HTML Best Practices",
      "Common HTML Mistakes to Avoid",
      "Debugging HTML (Browser DevTools)",
      "HTML Project Structure",
      "Deploying HTML Website",
      "HTML Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "HTML Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed HTML Concepts" },
      { type: "TEMPLATE", description: "HTML Code Template Auto Generate" },
      { type: "QUIZ", description: "HTML Quiz Auto Generate" }
    ]
  },
  {
    id: 18,
    title: "CSS - Styling Modern Websites",
    description: "Master CSS to create beautiful, responsive, and interactive websites.",
    target: "Web Design နှင့် Styling ကို ကျွမ်းကျင်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "CSS ဆိုတာဘာလဲ (Introduction)",
      "CSS Syntax နှင့် Structure",
      "Three Ways to Add CSS (Inline, Internal, External)",
      "CSS Selectors (Element, Class, ID)",
      "Universal Selector (*) နှင့် Grouping",
      "Descendant နှင့် Child Selectors",
      "Pseudo-class Selectors (:hover, :focus, :active)",
      "Pseudo-element Selectors (::before, ::after)",
      "Attribute Selectors အသုံးပြုခြင်း",
      "Colors ပေးခြင်း (Color Names, Hex, RGB, HSL)",
      "Background Properties (color, image, repeat, position)",
      "Background Attachment နှင့် Size",
      "Linear Gradients ဖန်တီးခြင်း",
      "Radial Gradients နှင့် Conic Gradients",
      "Text Properties (color, alignment, decoration, transform)",
      "Font Properties (family, size, weight, style)",
      "Web Fonts ထည့်သွင်းခြင်း (Google Fonts)",
      "Font Awesome Icons အသုံးပြုခြင်း",
      "Box Model (margin, border, padding, content)",
      "Margin Collapse နှင့် Negative Margins",
      "Border Styles နှင့် Border Radius",
      "Padding နှင့် Width/Height Calculation",
      "Display Property (block, inline, inline-block, none)",
      "Visibility နှင့် Opacity",
      "Position Property (static, relative, absolute, fixed, sticky)",
      "Z-index နှင့် Stacking Context",
      "Float နှင့် Clearfix Techniques",
      "Flexbox Introduction နှင့် Container Properties",
      "Flex Items (order, flex-grow, flex-shrink, flex-basis)",
      "Flexbox Alignment (justify-content, align-items)",
      "Flexbox Direction နှင့် Wrapping",
      "CSS Grid Introduction နှင့် Container Properties",
      "Grid Template Columns နှင့် Rows",
      "Grid Gap နှင့် Gaps",
      "Grid Item Placement (line-based, named areas)",
      "Grid Auto-fit နှင့် Auto-fill",
      "Responsive Design with Media Queries",
      "Mobile-First Approach",
      "Breakpoints သတ်မှတ်ခြင်း",
      "Container Queries အခြေခံ",
      "Relative Units (em, rem, %, vw, vh)",
      "Calc() Function အသုံးပြုခြင်း",
      "Min-width နှင့် Max-width",
      "Images in CSS (object-fit, object-position)",
      "CSS Filters (blur, brightness, contrast, grayscale)",
      "Transform Property (translate, rotate, scale, skew)",
      "Transitions နှင့် Timing Functions",
      "Animations (@keyframes)",
      "Animation Properties (duration, delay, iteration)",
      "Scroll-driven Animations",
      "CSS Variables (Custom Properties)",
      "CSS Reset နှင့် Normalize.css",
      "Specificity နှင့် Cascade",
      "!important Rule အသုံးပြုပုံ",
      "Inheritance နှင့် Initial Values",
      "CSS Box Sizing (content-box vs border-box)",
      "Overflow Property နှင့် Text Overflow",
      "White-space နှင့် Word Wrap",
      "Text Overflow နှင့် Line Clamp",
      "List Styles (type, position, image)",
      "Counter Styles နှင့် Custom Lists",
      "Table Styling (borders, spacing, alignment)",
      "Form Styling (inputs, buttons, focus states)",
      "CSS Grid vs Flexbox - When to Use What",
      "Responsive Images with srcset",
      "Picture Element နှင့် Art Direction",
      "CSS Subgrid အသုံးပြုခြင်း",
      "Logical Properties (margin-block, padding-inline)",
      "CSS Writing Modes",
      "Text Orientation နှင့် Direction",
      "CSS Shapes (circle, polygon, path)",
      "Masking နှင့် Clipping",
      "Blend Modes (multiply, screen, overlay)",
      "Backdrop Filter (Glassmorphism)",
      "CSS Columns (newspaper-style layout)",
      "CSS Counters (auto-numbering)",
      "Pointer Events နှင့် Touch Action",
      "Cursor နှင့် User Select",
      "Scroll Snap ဖြင့် Smooth Scrolling",
      "Sticky Positioning အသုံးပြုခြင်း",
      "CSS Aspect Ratio",
      "Color Mix Function (CSS Color Level 4)",
      "OKLCH နှင့် P3 Colors",
      "Nesting Rules အသုံးပြုခြင်း (CSS Nesting)",
      "Container Style Queries",
      "CSS Typography Advanced",
      "CSS Performance Optimization",
      "Critical CSS နှင့် Above-the-Fold",
      "CSS Architecture (BEM, OOCSS, SMACSS)",
      "CSS Framework Basics (Tailwind, Bootstrap)",
      "CSS Debugging (Browser DevTools)",
      "CSS Best Practices",
      "CSS Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "CSS Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed CSS Concepts" },
      { type: "TEMPLATE", description: "CSS Code Template Auto Generate" },
      { type: "QUIZ", description: "CSS Quiz Auto Generate" },
      { type: "PRACTICE", description: "CSS Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 19,
    title: "Bootstrap - Rapid Web Development",
    description: "Build responsive, mobile-first websites quickly with Bootstrap framework.",
    target: "Bootstrap ကို အသုံးပြု၍ ဝဘ်ဆိုဒ် အရင်းအမြစ်တည်ဆောက်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "Bootstrap ဆိုတာဘာလဲ (Introduction)",
      "Bootstrap Versions နှင့် History",
      "Bootstrap 5 New Features",
      "CDN ဖြင့် Bootstrap ထည့်သွင်းခြင်း",
      "Download လုပ်၍ Local တွင်သုံးခြင်း",
      "Bootstrap File Structure",
      "Container အမျိုးအစားများ (.container, .container-fluid)",
      "Grid System အခြေခံ (Rows နှင့် Columns)",
      "Grid Options (xs, sm, md, lg, xl, xxl)",
      "Column Sizing (1-12 columns)",
      "Column Wrapping နှင့် Column Breaks",
      "Vertical Alignment (align-items-start, center, end)",
      "Horizontal Alignment (justify-content-start, center, end)",
      "Gutters နှင့် Spacing",
      "Offsetting Columns (offset-md-*)",
      "Column Reordering (order-*)",
      "Typography (Headings, Display, Lead, Text utilities)",
      "Text Alignment နှင့် Text Wrapping",
      "Text Colors (primary, secondary, success, danger, etc.)",
      "Background Colors နှင့် Gradient Backgrounds",
      "Images အမျိုးအစားများ (img-fluid, img-thumbnail)",
      "Image Positioning (float-start, float-end)",
      "Figure နှင့် Figure Captions",
      "Tables အခြေခံ (table, table-striped, table-hover)",
      "Table Colors နှင့် Table Dark",
      "Table Responsive (.table-responsive)",
      "Figures နှင့် Captions",
      "Buttons အမျိုးအစားများ (btn-primary, btn-secondary, etc.)",
      "Button Sizes (btn-lg, btn-sm)",
      "Button States (active, disabled)",
      "Button Outline Styles",
      "Button Groups (btn-group)",
      "Toolbar နှင့် Nested Groups",
      "Button with Icons (Bootstrap Icons)",
      "Badges အသုံးပြုခြင်း",
      "Badge inside Headings နှင့် Buttons",
      "Progress Bars တည်ဆောက်ခြင်း",
      "Progress Bar Colors နှင့် Striped Effects",
      "Progress Bar Animation",
      "Alerts အမျိုးအစားများ",
      "Alert with Dismiss Button (.alert-dismissible)",
      "Card Component အခြေခံ",
      "Card Images နှင့် Card Body",
      "Card Header, Footer နှင့် Navigation",
      "Card Groups နှင့် Card Decks",
      "Card Columns (Masonry Layout)",
      "Dropdowns တည်ဆောက်ခြင်း",
      "Dropdown Items နှင့် Split Buttons",
      "Dropdown Directions (dropend, dropstart)",
      "Navbar အခြေခံ (navbar, navbar-brand)",
      "Navbar Colors နှင့် Responsive Toggle",
      "Navbar with Forms နှင့် Buttons",
      "Navbar Text နှင့် Fixed Positions",
      "Pagination အသုံးပြုခြင်း",
      "Breadcrumbs တည်ဆောက်ခြင်း",
      "List Groups အခြေခံ",
      "List Group with Badges နှင့် Links",
      "Forms အခြေခံ (form-control)",
      "Form Text နှင့် Validation Styles",
      "Input Groups တည်ဆောက်ခြင်း",
      "Floating Labels အသုံးပြုခြင်း",
      "Range Inputs နှင့် Checkboxes",
      "Switches နှင့် Radio Buttons",
      "Select Menu နှင့် File Input",
      "Custom CSS ဖန်တီးခြင်း (Customizing Bootstrap)",
      "Bootstrap Icons အသုံးပြုခြင်း",
      "Bootstrap JavaScript Plugins",
      "Modal တည်ဆောက်ခြင်း",
      "Tabs နှင့် Pill Navigation",
      "Tooltips နှင့် Popovers",
      "Toast Notifications",
      "Scrollspy နှင့် Scroll Behavior",
      "Offcanvas Sidebar အသုံးပြုခြင်း",
      "Carousel Slider တည်ဆောက်ခြင်း",
      "Accordion Component အသုံးပြုခြင်း",
      "Bootstrap Utilities (Border, Shadow, Spacing)",
      "Display Utilities (d-none, d-block, d-flex)",
      "Flexbox Utilities in Bootstrap",
      "Bootstrap နှင့် React/Other Frameworks",
      "Bootstrap အကောင်းဆုံးအသုံးပြုနည်း",
      "Bootstrap Project Example",
      "Bootstrap Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Bootstrap Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed Bootstrap Concepts" },
      { type: "TEMPLATE", description: "Bootstrap Code Template Auto Generate" },
      { type: "QUIZ", description: "Bootstrap Quiz Auto Generate" },
      { type: "PRACTICE", description: "Bootstrap Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 20,
    title: "Tailwind CSS - Utility-First Framework",
    description: "Build modern websites rapidly with Tailwind CSS utility classes.",
    target: "Tailwind CSS ကို အသုံးပြု၍ ဝဘ်ဆိုဒ် အလှလှတည်ဆောက်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "Tailwind CSS ဆိုတာဘာလဲ (Introduction)",
      "Utility-First Concept နားလည်ခြင်း",
      "Tailwind CSS vs Bootstrap နှိုင်းယှဉ်ချက်",
      "Tailwind CSS Installation (CDN, npm, CLI)",
      "Tailwind CSS Setup with Vite/React",
      "Tailwind CSS Configuration (tailwind.config.js)",
      "Content Detection နှင့် File Scanning",
      "Default Theme နှင့် Extending Theme",
      "Custom Colors ထည့်သွင်းခြင်း",
      "Custom Spacing နှင့် Sizing",
      "Custom Fonts နှင့် Typography",
      "Arbitrary Values (Square Bracket Notation)",
      "Arbitrary Properties နှင့် Variants",
      "Utility Classes အခြေခံ (p-*, m-*)",
      "Margin နှင့် Padding Shorthands",
      "Individual Sides (mt-4, mb-4, ml-4, mr-4)",
      "Horizontal နှင့် Vertical Shorthands (mx-*, my-*)",
      "Negative Values (-m-*, -mt-*)",
      "Width Utilities (w-*, min-w-*, max-w-*)",
      "Height Utilities (h-*, min-h-*, max-h-*)",
      "Percentage-based Sizing (w-1/2, h-full)",
      "Viewpoint Units (w-screen, h-screen)",
      "Container နှင့် Centering",
      "Text Utilities (text-*, text-color, text-opacity)",
      "Font Family (font-sans, font-serif, font-mono)",
      "Font Size (text-xs မှ text-9xl)",
      "Font Weight (font-light မှ font-black)",
      "Line Height (leading-*, leading-none)",
      "Text Alignment (text-left, center, right, justify)",
      "Text Decoration နှင့် Truncate",
      "Text Transform (uppercase, lowercase, capitalize)",
      "Colors အခြေခံ (text-*, bg-*, border-*)",
      "Color Palette (slate, gray, zinc, neutral, red, etc.)",
      "Opacity Utilities (text-opacity-50, bg-opacity-75)",
      "Arbitrary Colors ([#123456], [rgba(...)] )",
      "Background Image (bg-*, bg-gradient-to-*)",
      "Background Size နှင့် Position",
      "Background Attachment နှင့် Repeat",
      "Border Width နှင့် Colors",
      "Border Radius (rounded-*, rounded-full, rounded-none)",
      "Border Style (border-solid, border-dashed, border-dotted)",
      "Divide Width နှင့် Divide Color",
      "Ring Utilities (ring-*, ring-offset-*)",
      "Outline နှင့် Outline Offset",
      "Flexbox Container (flex, inline-flex)",
      "Flex Direction (flex-col, flex-row, flex-row-reverse)",
      "Flex Wrapping (flex-wrap, flex-nowrap, flex-wrap-reverse)",
      "Flex Grow နှင့် Shrink",
      "Flex Order (order-1 မှ order-last)",
      "Justify Content (justify-start, center, end, between, around)",
      "Align Items (items-start, center, end, stretch, baseline)",
      "Align Content (content-start, center, end, between)",
      "Align Self (self-auto, start, center, end, stretch)",
      "Gap Utilities (gap-*, gap-x-*, gap-y-*)",
      "Grid Container (grid, inline-grid)",
      "Grid Template Columns (grid-cols-1 မှ grid-cols-12)",
      "Grid Template Rows (grid-rows-*, auto-rows-*)",
      "Column Utilities (columns-1 မှ columns-3)",
      "Grid Column Start/End (col-span-*, col-start-*, col-end-*)",
      "Grid Row Start/End (row-span-*, row-start-*, row-end-*)",
      "Grid Auto Flow (grid-flow-row, grid-flow-col)",
      "Position (static, relative, absolute, fixed, sticky)",
      "Top/Right/Bottom/Left (top-*, right-*, bottom-*, left-*)",
      "Z-index (z-0 မှ z-50)",
      "Visibility (visible, invisible)",
      "Display (block, inline-block, inline, hidden, contents)",
      "Float နှင့် Clear",
      "Overflow (overflow-auto, hidden, scroll, visible)",
      "Object Fit (object-cover, contain, fill, none)",
      "Object Position",
      "Aspect Ratio (aspect-video, aspect-square)",
      "Table Layout (table-auto, table-fixed)",
      "Table Caption Side (caption-top, caption-bottom)",
      "Transition Property (transition, transition-all, transition-colors)",
      "Transition Duration (duration-*, duration-[...])",
      "Transition Timing Function (ease-*, ease-in, ease-out)",
      "Transition Delay (delay-*)",
      "Transform (transform, rotate-*, scale-*, translate-*)",
      "Transform Origin",
      "Animation (animate-spin, ping, pulse, bounce)",
      "Keyframes Customization",
      "Custom Animations ထည့်သွင်းခြင်း",
      "Filter (blur, brightness, contrast, grayscale, hue-rotate)",
      "Backdrop Filter (backdrop-blur, backdrop-brightness)",
      "Mix Blend Mode",
      "Gradient Color Stops",
      "Hover States (hover:bg-*, hover:text-*)",
      "Focus States (focus:outline, focus:ring-*)",
      "Active States (active:bg-*)",
      "Disabled States (disabled:opacity-50)",
      "Media Queries (md:*, lg:*, xl:*, 2xl:*)",
      "Min-width and Max-width Breakpoints",
      "Print Styles (print:bg-white, print:text-black)",
      "Dark Mode (dark:bg-*, dark:text-*)",
      "Dark Mode with Media Strategy",
      "Dark Mode with Class Strategy",
      "Responsive Design Best Practices",
      "Mobile-First Approach",
      "Hover-First Design",
      "Using Plugins (@tailwindcss/forms, @tailwindcss/typography)",
      "Building Reusable Components",
      "Component Extraction (@apply directive)",
      "When to Use @apply vs Utility Classes",
      "Performance Optimization",
      "PurgeCSS နှင့် Content Scanning",
      "Production Build",
      "Tailwind CSS with React",
      "Tailwind CSS with Vue",
      "Tailwind CSS with Other Frameworks",
      "Debug Mode (debug:*)",
      "Using Pros နှင့် Cons",
      "Tailwind CSS Project Example",
      "Tailwind CSS Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Tailwind CSS Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed Tailwind CSS Concepts" },
      { type: "TEMPLATE", description: "Tailwind CSS Code Template Auto Generate" },
      { type: "QUIZ", description: "Tailwind CSS Quiz Auto Generate" },
      { type: "PRACTICE", description: "Tailwind CSS Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 21,
    title: "JavaScript - Programming Foundation",
    description: "Master JavaScript programming from basics to advanced concepts.",
    target: "JavaScript ကို စလေ့လာပြီး Web Development လုပ်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "JavaScript ဆိုတာဘာလဲ (Introduction)",
      "JavaScript History နှင့် Evolution",
      "ECMAScript နှင့် ES6+ Features",
      "Setting Up Development Environment",
      "Browser Console အသုံးပြုနည်း",
      "First JavaScript Program",
      "Comments in JavaScript (Single/Multi-line)",
      "Variables (var, let, const)",
      "Variable Scope (Global, Function, Block)",
      "Data Types (Primitive vs Reference)",
      "Numbers နှင့် Math Operations",
      "Strings အခြေခံ (Concatenation, Template Literals)",
      "String Methods (length, slice, substring, replace)",
      "String Methods (toUpperCase, toLowerCase, trim)",
      "String Searching (indexOf, lastIndexOf, includes)",
      "String Extracting (slice, substr)",
      "Template Strings (Backticks)",
      "Booleans နှင့် Comparison Operators",
      "Logical Operators (&&, ||, !)",
      "Type Conversion (Implicit vs Explicit)",
      "typeof Operator အသုံးပြုခြင်း",
      "Arrays အခြေခံ (Creation, Access)",
      "Array Methods (push, pop, shift, unshift)",
      "Array Methods (splice, slice, concat)",
      "Array Methods (indexOf, find, findIndex)",
      "Array Methods (filter, map, reduce)",
      "Array Methods (forEach, some, every)",
      "Array Methods (sort, reverse, flat)",
      "Array Destructuring",
      "Multi-dimensional Arrays",
      "Objects အခြေခံ (Creation, Properties)",
      "Object Methods နှင့် this Keyword",
      "Object Destructuring",
      "Object Methods (keys, values, entries)",
      "Spread Operator in Objects",
      "Nested Objects နှင့် Accessing",
      "Functions အခြေခံ (Declaration, Expression)",
      "Parameters နှင့် Arguments",
      "Return Statement နှင့် Returning Values",
      "Arrow Functions (=>)",
      "Default Parameters",
      "Rest Parameters (...)",
      "Callback Functions",
      "Higher-Order Functions",
      "Closures နားလည်ခြင်း",
      "Hoisting ဆိုတာဘာလဲ",
      "Scope Chain နှင့် Lexical Scope",
      "IIFE (Immediately Invoked Function Expression)",
      "Conditional Statements (if, else if, else)",
      "Switch Statement",
      "Ternary Operator",
      "Truthy နှင့် Falsy Values",
      "Loops (for, while, do-while)",
      "For...of Loop",
      "For...in Loop",
      "Break နှင့် Continue Statements",
      "Error Handling (try, catch, finally)",
      "Throwing Errors (throw)",
      "Custom Error Classes",
      "Date နှင့် Time Objects",
      "Math Object Methods (random, floor, ceil, round)",
      "JSON ဆိုတာဘာလဲ",
      "JSON.parse() နှင့် JSON.stringify()",
      "Local Storage အသုံးပြုခြင်း",
      "Session Storage အသုံးပြုခြင်း",
      "Cookies အခြေခံ",
      "DOM ဆိုတာဘာလဲ (Document Object Model)",
      "Selecting Elements (getElementById, querySelector)",
      "Selecting Multiple Elements",
      "Traversing DOM (parent, child, sibling)",
      "Creating Elements (createElement)",
      "Adding Elements to DOM (appendChild, insertBefore)",
      "Removing Elements (removeChild, remove)",
      "Modifying Element Content (innerHTML, textContent)",
      "Modifying Attributes (setAttribute, getAttribute)",
      "Modifying CSS Styles (style property)",
      "Adding/Removing Classes (classList)",
      "Event Listeners (addEventListener)",
      "Event Object နှင့် Event Properties",
      "Event Types (click, mouseover, keydown, submit)",
      "Event Propagation (Bubbling, Capturing)",
      "Event Delegation",
      "Prevent Default Behavior",
      "Form Validation with JavaScript",
      "Input Validation Techniques",
      "Regular Expressions အခြေခံ",
      "Regex Methods (test, match, replace, search)",
      "Regex Patterns (Character classes, Quantifiers)",
      "Async JavaScript နှင့် Synchronous",
      "setTimeout နှင့် setInterval",
      "Callback Hell နှင့် Solutions",
      "Promises အခြေခံ (Creation, States)",
      "Promise Methods (then, catch, finally)",
      "Promise.all, Promise.race, Promise.allSettled",
      "Async/Await Syntax",
      "Error Handling in Async/Await",
      "Fetch API အသုံးပြုခြင်း",
      "HTTP Requests (GET, POST, PUT, DELETE)",
      "Headers နှင့် Request Options",
      "Handling API Responses",
      "Async Iterations (for await...of)",
      "Generators နားလည်ခြင်း",
      "Iterators နှင့် Iterable Protocol",
      "Symbols နှင့် Well-known Symbols",
      "Map နှင့် Set Data Structures",
      "WeakMap နှင့် WeakSet",
      "Object Oriented Programming (OOP)",
      "Constructor Functions",
      "Classes အခြေခံ (class, constructor)",
      "Inheritance (extends, super)",
      "Static Methods နှင့် Properties",
      "Getters နှင့် Setters",
      "Private Fields (#)",
      "Encapsulation နှင့် Abstraction",
      "Polymorphism နှင့် Method Overriding",
      "Module Systems (ES6 Modules)",
      "Import နှင့် Export",
      "Default vs Named Exports",
      "Dynamic Imports",
      "Web APIs Overview",
      "Geolocation API",
      "Canvas API အခြေခံ",
      "Audio/Video APIs",
      "Web Storage APIs",
      "Web Workers နားလည်ခြင်း",
      "Service Workers နှင့် PWA Basics",
      "Debouncing နှင့် Throttling",
      "Memoization နည်းလမ်းများ",
      "Currying Functions",
      "Compose နှင့် Pipe Functions",
      "Pure Functions နှင့် Immutability",
      "Recursion နှင့် Base Cases",
      "Deep Copy vs Shallow Copy",
      "Destructuring Assignment",
      "Restructuring (Rest/Spread in Objects)",
      "Optional Chaining (?.)",
      "Nullish Coalescing (??)",
      "BigInt နှင့် BigInt Arithmetic",
      "Proxy နှင့် Reflect APIs",
      "Internationalization API (Intl)",
      "Performance Optimization",
      "Memory Management နှင့် Garbage Collection",
      "Best Practices in JavaScript",
      "Common Mistakes to Avoid",
      "Debugging Techniques",
      "JavaScript Project Structure",
      "JavaScript Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "JavaScript Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed JavaScript Concepts" },
      { type: "TEMPLATE", description: "JavaScript Code Template Auto Generate" },
      { type: "QUIZ", description: "JavaScript Quiz Auto Generate" },
      { type: "PRACTICE", description: "JavaScript Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 22,
    title: "Git & GitHub - Version Control System",
    description: "Master version control with Git and collaboration on GitHub.",
    target: "Git နှင့် GitHub ကို လေ့လာပြီး Team နှင့် Project တွေမှာ ပူးပေါင်းလိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "Version Control ဆိုတာဘာလဲ (Introduction)",
      "Git ရဲ့ History နှင့် Background",
      "Git နှင့် GitHub ကွာခြားချက်",
      "Git Installation (Windows, macOS, Linux)",
      "Git Configuration (git config)",
      "First-Time Git Setup (User Name, Email)",
      "Git အသုံးပြုရန် Command Line Basics",
      "Creating a Repository (git init)",
      "Cloning a Repository (git clone)",
      "Git Status စစ်ဆေးခြင်း",
      "Staging Area နားလည်ခြင်း",
      "Adding Files to Staging (git add)",
      "Committing Changes (git commit)",
      "Commit Message Writing Best Practices",
      "Viewing Commit History (git log)",
      "Git မှာ File ကို Ignore လုပ်ခြင်း (.gitignore)",
      "Working with Branches (git branch)",
      "Creating New Branches",
      "Switching Branches (git checkout, git switch)",
      "Creating and Switching Branches at Once",
      "Merging Branches (git merge)",
      "Merge Conflicts ဖြေရှင်းနည်း",
      "Deleting Branches",
      "Renaming Branches",
      "GitHub Account Setup",
      "Creating GitHub Repository",
      "Remote Repository နှင့် Local Repository ချိတ်ဆက်ခြင်း",
      "Pushing to Remote (git push)",
      "Pulling Changes (git pull)",
      "Fetching Changes (git fetch)",
      "SSH Key Setup for GitHub",
      "HTTPS vs SSH for Remote Connection",
      "GitHub Pages ဖြင့် Website Host လုပ်ခြင်း",
      "Pull Requests ဖန်တီးခြင်း",
      "Reviewing Pull Requests",
      "Merging Pull Requests",
      "Forking Repositories",
      "Contributing to Open Source Projects",
      "GitHub Issues အသုံးပြုခြင်း",
      "GitHub Projects and Kanban Boards",
      "GitHub Wiki Documentation",
      "GitHub Releases",
      "Git Tags (Annotated vs Lightweight)",
      "Reverting Commits (git revert)",
      "Resetting Commits (git reset)",
      "Checking Out Previous Commits",
      "Stashing Changes (git stash)",
      "Git Blame နှင့် File History",
      "Git Diff အသုံးပြုခြင်း",
      "GitHub CLI (gh) အခြေခံ",
      "GitHub Actions (CI/CD Intro)",
      "GitHub Security Features (Dependabot, Security Tab)",
      "GitHub Education Benefits",
      "GitHub Copilot (AI Pair Programming)",
      "Advanced Git Commands (cherry-pick, rebase)",
      "Interactive Rebase",
      "Git Workflow Strategies (Git Flow, Trunk-Based)",
      "Best Practices for Version Control",
      "Git & GitHub Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "Git & GitHub Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed Version Control Concepts" },
      { type: "TEMPLATE", description: "Git Command Template Auto Generate" },
      { type: "QUIZ", description: "Git & GitHub Quiz Auto Generate" },
      { type: "PRACTICE", description: "Git Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 23,
    title: "PHP - Server-Side Programming",
    description: "Master PHP for building dynamic web applications and server-side logic.",
    target: "PHP ကို စလေ့လာပြီး Backend Development လုပ်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "PHP ဆိုတာဘာလဲ (Introduction)",
      "PHP History နှင့် Evolution",
      "PHP vs Other Server-Side Languages",
      "Setting Up Development Environment (XAMPP/WAMP/LAMP)",
      "PHP Installation and Configuration",
      "First PHP Program (Hello World)",
      "PHP Syntax (Opening tag, Statements)",
      "Comments in PHP (Single-line, Multi-line)",
      "Variables in PHP ($ symbol)",
      "Data Types (String, Integer, Float, Boolean)",
      "Arrays in PHP (Indexed, Associative, Multidimensional)",
      "Constants in PHP (define(), const)",
      "Type Juggling and Type Casting",
      "Operators (Arithmetic, Assignment)",
      "Comparison Operators (==, ===, !=, !==, <, >)",
      "Logical Operators (&&, ||, !, and, or)",
      "Increment/Decrement Operators",
      "String Operators (Concatenation)",
      "Arrays Operators (Union, Equality)",
      "If Statement",
      "Else If Statement",
      "Switch Statement",
      "Ternary Operator (? :)",
      "Null Coalescing Operator (??)",
      "Spaceship Operator (<=>)",
      "For Loop",
      "While Loop",
      "Do...While Loop",
      "Foreach Loop",
      "Break and Continue Statements",
      "Functions in PHP",
      "Function Parameters and Arguments",
      "Default Parameter Values",
      "Returning Values from Functions",
      "Variable Scope (Global, Local, Static)",
      "Variable-length Argument Lists (...$args)",
      "Arrow Functions (fn() =>)",
      "Working with Strings (strlen, strpos, substr)",
      "String Manipulation (strtolower, strtoupper, ucwords)",
      "String Searching (strstr, stristr)",
      "String Replacing (str_replace, strtr)",
      "Regular Expressions (preg_match, preg_replace)",
      "Array Functions (count, array_push, array_pop)",
      "Array Functions (array_shift, array_unshift)",
      "Array Functions (array_merge, array_combine)",
      "Array Functions (array_slice, array_splice)",
      "Array Functions (array_keys, array_values)",
      "Array Functions (in_array, array_search)",
      "Array Functions (sort, rsort, asort, ksort)",
      "Multidimensional Arrays",
      "Superglobals ($_GET, $_POST, $_REQUEST)",
      "$_SERVER Array",
      "$_SESSION (Session Management)",
      "$_COOKIE (Cookie Management)",
      "$_FILES (File Uploads)",
      "$_ENV and $_SERVER Variables",
      "Form Handling (GET vs POST methods)",
      "Form Validation (Required Fields, Email)",
      "Sanitizing User Input",
      "Password Hashing (password_hash, password_verify)",
      "File Handling (fopen, fread, fwrite, fclose)",
      "File Operations (file_get_contents, file_put_contents)",
      "Checking File Existence (file_exists)",
      "Directory Functions (mkdir, rmdir, opendir)",
      "Including Files (include, require, include_once, require_once)",
      "Error Handling (try, catch, throw)",
      "Custom Error Handling (set_error_handler)",
      "Exception Handling (Exception Class)",
      "Creating Custom Exceptions",
      "PDO (PHP Data Objects) Introduction",
      "PDO Database Connection",
      "PDO Prepared Statements",
      "PDO Fetch Methods (fetch, fetchAll, fetchObject)",
      "MySQLi Extension (Object-Oriented)",
      "MySQLi CRUD Operations (Create, Read, Update, Delete)",
      "SQL Injection Prevention",
      "XSS Prevention (htmlspecialchars)",
      "CSRF Protection",
      "Object-Oriented PHP (Classes and Objects)",
      "Constructor (__construct) and Destructor (__destruct)",
      "Visibility (Public, Private, Protected)",
      "Inheritance in PHP",
      "Abstract Classes and Methods",
      "Interfaces in PHP",
      "Traits in PHP",
      "Static Properties and Methods",
      "Magic Methods (__get, __set, __call)",
      "Magic Methods (__toString, __invoke)",
      "Magic Methods (__clone, __debugInfo)",
      "Namespaces in PHP",
      "Autoloading Classes (spl_autoload_register)",
      "Composer Dependency Manager",
      "Composer.json and Autoloading",
      "Installing Packages with Composer",
      "Using Third-party Libraries (PHPMailer, Guzzle)",
      "REST API Development with PHP",
      "JSON Handling (json_encode, json_decode)",
      "XML Parsing (SimpleXML, DOMDocument)",
      "cURL Library (HTTP Requests)",
      "File Downloads with PHP",
      "File Upload Handling (Multipart/form-data)",
      "Image Processing (GD Library)",
      "Thumbnail Creation",
      "Session Security",
      "Cookie Security (HttpOnly, Secure, SameSite)",
      "HTTPS and SSL/TLS",
      "Password Policies and Best Practices",
      "Two-Factor Authentication",
      "Rate Limiting and Throttling",
      "Logging Errors (error_log)",
      "Debugging Techniques (Xdebug, var_dump)",
      "Performance Optimization",
      "Caching Strategies",
      "PHP 8 Features (Named Arguments, Attributes)",
      "Match Expression (PHP 8)",
      "Union Types (PHP 8)",
      "Mixed Type (PHP 8)",
      "Constructor Property Promotion (PHP 8)",
      "Nullsafe Operator (?->) (PHP 8)",
      "Match Expression Improvements (PHP 8.1)",
      "Enums (PHP 8.1)",
      "Readonly Properties (PHP 8.1)",
      "New in Initializers (PHP 8.2)",
      "Disjunctive Normal Form Types (PHP 8.2)",
      "Constants in Traits (PHP 8.2)",
      "MySQL Extension Deprecation",
      "Project Structure Best Practices",
      "Security Audit Checklist",
      "Deployment to Production Server",
      "PHP Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "PHP Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed PHP Concepts" },
      { type: "TEMPLATE", description: "PHP Code Template Auto Generate" },
      { type: "QUIZ", description: "PHP Quiz Auto Generate" },
      { type: "PRACTICE", description: "PHP Practice Exercise Auto Generate" }
    ]
  },
  {
    id: 24,
    title: "MySQL - Database Management System",
    description: "Master MySQL for effective database design, management, and optimization.",
    target: "MySQL ကို စလေ့လာပြီး Database Development လုပ်လိုသူများအတွက်",
    category: "Web Development",
    topics: [
      "MySQL ဆိုတာဘာလဲ (Introduction)",
      "MySQL History နှင့် Oracle Ownership",
      "RDBMS ဆိုတာဘာလဲ (Relational Database Management System)",
      "MySQL vs Other Databases (PostgreSQL, MariaDB, SQLite)",
      "MySQL Installation (Windows, macOS, Linux)",
      "MySQL Configuration Files (my.cnf, my.ini)",
      "MySQL Server စတင်ခြင်းနှင့် ရပ်စဲခြင်း",
      "MySQL Command Line Client (mysql)",
      "MySQL Workbench အသုံးပြုခြင်း",
      "phpMyAdmin အခြေခံ",
      "Database ဆိုတာဘာလဲ",
      "Creating Database (CREATE DATABASE)",
      "Selecting Database (USE)",
      "Dropping Database (DROP DATABASE)",
      "Showing Databases (SHOW DATABASES)",
      "Database များကို List လုပ်ခြင်း",
      "Tables ဆိုတာဘာလဲ",
      "Creating Tables (CREATE TABLE)",
      "Column Data Types (INT, VARCHAR, TEXT, DATE, DATETIME)",
      "Column Data Types (DECIMAL, FLOAT, BOOLEAN, ENUM)",
      "Column Attributes (NOT NULL, DEFAULT, AUTO_INCREMENT)",
      "Primary Keys သတ်မှတ်ခြင်း",
      "Foreign Keys သတ်မှတ်ခြင်း",
      "Unique Constraints",
      "CHECK Constraints",
      "Table Comments",
      "Viewing Table Structure (DESCRIBE, SHOW COLUMNS)",
      "Modifying Tables (ALTER TABLE)",
      "Adding Columns (ADD COLUMN)",
      "Modifying Columns (MODIFY COLUMN, CHANGE COLUMN)",
      "Dropping Columns (DROP COLUMN)",
      "Renaming Tables (RENAME TABLE)",
      "Dropping Tables (DROP TABLE)",
      "Temporary Tables (CREATE TEMPORARY TABLE)",
      "Cloning Tables",
      "Inserting Data (INSERT INTO)",
      "Inserting Multiple Rows",
      "Inserting into Specific Columns",
      "Inserting from Another Table",
      "Updating Data (UPDATE)",
      "Updating with Conditions (WHERE)",
      "Updating Multiple Columns",
      "Deleting Data (DELETE FROM)",
      "Deleting with Conditions (WHERE)",
      "Truncating Tables (TRUNCATE TABLE)",
      "Reading Data (SELECT)",
      "Selecting Specific Columns",
      "Selecting All Columns (*)",
      "Using WHERE Clause for Filtering",
      "Comparison Operators (=, <>, <, >, <=, >=)",
      "Logical Operators (AND, OR, NOT)",
      "BETWEEN Operator",
      "IN Operator",
      "LIKE Operator (Pattern Matching)",
      "Wildcards (% and _)",
      "IS NULL and IS NOT NULL",
      "DISTINCT Keyword",
      "LIMIT Clause",
      "OFFSET and LIMIT",
      "ORDER BY Clause (ASC, DESC)",
      "Sorting by Multiple Columns",
      "Aggregate Functions (COUNT, SUM, AVG, MIN, MAX)",
      "GROUP BY Clause",
      "HAVING Clause",
      "Aliases (Column and Table Aliases)",
      "Joins (INNER JOIN)",
      "Joins (LEFT JOIN, RIGHT JOIN)",
      "Joins (FULL OUTER JOIN)",
      "Self Joins",
      "Cross Joins",
      "Natural Joins",
      "Subqueries (Nested Queries)",
      "Correlated Subqueries",
      "EXISTS and NOT EXISTS",
      "UNION and UNION ALL",
      "INTERSECT and MINUS",
      "Views (CREATE VIEW)",
      "Updating Views",
      "Dropping Views",
      "Stored Procedures (CREATE PROCEDURE)",
      "Calling Stored Procedures",
      "Dropping Stored Procedures",
      "Stored Functions (CREATE FUNCTION)",
      "Differences between Procedures and Functions",
      "Triggers (CREATE TRIGGER)",
      "BEFORE and AFTER Triggers",
      "Dropping Triggers",
      "Transactions (START TRANSACTION)",
      "COMMIT and ROLLBACK",
      "SAVEPOINT and ROLLBACK TO",
      "ACID Properties",
      "Indexing (CREATE INDEX)",
      "Types of Indexes (B-tree, Hash, Full-text)",
      "Composite Indexes",
      "Dropping Indexes (DROP INDEX)",
      "Query Optimization",
      "EXPLAIN Statement",
      "Using EXPLAIN to Analyze Queries",
      "Normalization (1NF, 2NF, 3NF)",
      "Denormalization",
      "Database Security (User Accounts)",
      "Creating Users (CREATE USER)",
      "Granting Privileges (GRANT)",
      "Revoking Privileges (REVOKE)",
      "Role-Based Access Control",
      "Backing Up Databases (mysqldump)",
      "Restoring Databases",
      "Point-in-Time Recovery",
      "Replication Basics",
      "MySQL Partitioning",
      "JSON Data Type (MySQL 5.7+)",
      "Generated Columns",
      "Window Functions (MySQL 8.0+)",
      "Common Table Expressions (CTE) (MySQL 8.0+)",
      "Recursive CTEs (MySQL 8.0+)",
      "MySQL Summary နှင့် Next Steps"
    ],
    aiFeatures: [
      { type: "EXPLAIN", description: "MySQL Lesson explanation in Myanmar" },
      { type: "DEEP_EXPLAIN", description: "Detailed Database Concepts" },
      { type: "TEMPLATE", description: "SQL Query Template Auto Generate" },
      { type: "QUIZ", description: "MySQL Quiz Auto Generate" },
      { type: "PRACTICE", description: "MySQL Practice Exercise Auto Generate" }
    ]
  }
];
